### PR TITLE
SPAzureAccessControlServiceAppProxy/SPOAppPrincipalMgmtServiceAppProxy: Add new resources for ACS and SPO app mgmt

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
Add new resources for Azure Access Control Service Application Proxy and SharePoint Online Application Principal Management Service Application Proxy

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1146)

### CODE REVIEW

**Comment by ykuijs** [comment]
To run the new CI system locally:

- First run '.\build.ps1 -Tasks noop -ResolveDependency' to download all the dependencies to the output folder
- Then run '.\build.ps1 -Tasks Build' to build the module
- Finally run '.\build.ps1 -Tasks Test' to run all Unit tests or the individual Pester test in the test folder.

I am going to update the documentation, but haven't got around to this yet ;-)

**Comment by jensotto** [comment]
I used the debugger in VS Code, but that did not work (will it work in the future).
I tried using the build and test tasks but the test task takes forever to complete, and I can't figure out how to run a specific test. could you give me an example?

**Comment by jensotto** [comment]
@ykuijs any input on my latest reply?

**Comment by ykuijs** [comment]
Sorry for not replying any sooner! Have been working on other things and this slipped through. Thanks for the reminder.

If you ran the "./build.ps1 -Tasks Build" script in the root of the repo, you can then go to the tests folder (cd tests\Unit\SharePointDsc) and run your Pester test file (.\SharePointDsc.[resource].Tests.ps1). That should run your Pester test correctly.

**Comment by ykuijs** [comment]
There is another issue with Pester tests, that is not caused by your PR. I will submit a new PR, which will fix this issue. After that is merged you can update your PR with this update.

**Comment by ykuijs** [comment]
Please update from Master to pull in the fixes for the failing Pester test

**Comment by jensotto** [comment]
I've merged the changes from master now

**Comment by ykuijs** [comment]
@jensotto Great work, thanks a lot!

**Pull request merged**
