### PR TITLE
Fixing issue #1252

### LINKED ISSUE #1252: SPInstallPrereqs Fails with Exit Code 1620
#### Details of the scenario you tried and the problem that is occurring

Due to the file http://go.microsoft.com/fwlink/?LinkId=622997 (SQL 2012 native client) is no longer available, SharePoint 2016 prerequisite installer cannot properly run and returns error.

#### Verbose logs showing the problem

```
PowerShell DSC resource MSFT_SPInstallPrereqs  failed to execute Set-TargetResource functionality with error message:
The prerequisite installer ran with the following unknown exit code 1620
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SWAZSERVER01.c0nt0s00.local
```

#### Suggested solution to the issue

For example, one can use SQL 2012 SP4 native client. I tested it in my sandbox but not sure if it is fully supported by Microsoft:

```
        File SPLocalMediaEnsure {
            SourcePath = $env:SP_MEDIA_UNC
            DestinationPath = "C:\Install\SP_MEDIA"
            Recurse = $true
            Type = "Directory"
            Credential = $MediaShareCredential
        }

        xRemoteFile SQLNCli
        {
            Uri             = "https://download.microsoft.com/download/F/3/C/F3C64941-22A0-47E9-BC9B-1A19B4CA3E88/ENU/x64/sqlncli.msi"
            DestinationPath = "C:\Install\SP_MEDIA\2016\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
            MatchSource     = $false
            DependsOn       = "[File]SPLocalMediaEnsure"
        }

        Package SQLNCli
        {
            Path        = "C:\Install\SP_MEDIA\2016\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
            Name        = "Microsoft SQL Server 2012 Native Client "
            ProductId   = "B9274744-8BAE-4874-8E59-2610919CD419"
            Arguments   = "/qn /norestart IACCEPTSQLNCLILICENSETERMS=YES"
            DependsOn   = "[xRemoteFile]SQLNCli"
        }

        SPInstallPrereqs SPPrereqsInstalled
        {
            IsSingleInstance    = "Yes"
            InstallerPath       = "C:\Install\SP_MEDIA\2016\SharePoint\Prerequisiteinstaller.exe"
            OnlineMode          = $true
            DependsOn           = "[File]SPLocalMediaEnsure", "[Package]SQLNCli"
        }
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
        SPInstallPrereqs SPPrereqsInstalled
        {
            IsSingleInstance    = "Yes"
            InstallerPath       = "C:\Install\SP_MEDIA\2016\SharePoint\Prerequisiteinstaller.exe"
            OnlineMode          = $true
            DependsOn           = "[File]SPLocalMediaEnsure", "[Package]SQLNCli"
        }
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2016

#### Version of the DSC module that was used

4.2.0

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This issue updates the documentation of SPInstallPrereqs to clarify an download issue with the SQL Server 2012 Native Client being unavailable on the Microsoft site when using Online mode.

#### This Pull Request (PR) fixes the following issues

- Fixes #1252 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256)

### CODE REVIEW

**Review by NikCharlebois — COMMENTED** [review]
2 small things

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-:-MLwaEBy7bX5j09QSfg5:b-8jjdvz)* status: all files reviewed, 2 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md, line 54 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-MLw_xZD-ZdDIFpAjy3j:-MLw_xZEDxDsWJUO0UJF:bgjilw) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/cf4f995b9e8b7f255443b729112ea03fee49a85a/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md#L54)):*
> ```Markdown
> 
> NOTE:
> The SQL Server 2012 Native Client has been removed as download from the
> ```

'as a download'
___
*[SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md, line 68 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-MLwa5HyCFIzlGyH3Owy:-MLwa5HyCFIzlGyH3Owz:bg1xvlu) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/cf4f995b9e8b7f255443b729112ea03fee49a85a/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md#L68)):*
> ```Markdown
>     DestinationPath = "C:\Install\SharePoint\prerequisiteinstallerfiles\sqlncli.msi"
>     MatchSource     = $false
>     DependsOn       = "[File]SPLocalMediaEnsure"
> ```

Maybe remove this part from the example as it will surely cause confusion to newbies since this SPLocalMediaEnsure resource is not there.

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256)* status: all files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md, line 54 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-MLw_xZD-ZdDIFpAjy3j:-MLwcflF33vClF1rEO-f:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/cf4f995b9e8b7f255443b729112ea03fee49a85a/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md#L54)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

'as a download'
</blockquote></details>

Done.
___
*[SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md, line 68 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-MLwa5HyCFIzlGyH3Owy:-MLwckR65PcAqYmgQwrR:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/cf4f995b9e8b7f255443b729112ea03fee49a85a/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md#L68)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Maybe remove this part from the example as it will surely cause confusion to newbies since this SPLocalMediaEnsure resource is not there.
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md, line 68 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-MLwa5HyCFIzlGyH3Owy:-MLwd2htDSVySxRXrLoY:bei8x1g) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/cf4f995b9e8b7f255443b729112ea03fee49a85a/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md#L68)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually I meant only the DependsOn clause, the rest is still valuable I think.

**Review by NikCharlebois — COMMENTED** [review]
Just one small thing

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-:-MLwdDQt47FcjQAzSR6t:bnbzhos)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md, line 68 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-MLwa5HyCFIzlGyH3Owy:-MLwgQWQCpJz5l_Y_rKL:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/cf4f995b9e8b7f255443b729112ea03fee49a85a/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md#L68)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Actually I meant only the DependsOn clause, the rest is still valuable I think. 
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1256#-:-MLwiJIf-LaLKSq6kAYq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ykuijs** [comment]
PR no longer required. PG solved the issue by updating the used permalink.

**Pull request closed without merging**
