### PR TITLE
Bugfix

### LINKED ISSUE #1269: [SPWordAutomationServiceApp] Creating the service application doesn't add it to the default proxy group
#### Details of the scenario you tried and the problem that is occurring
Most service applications are automatically added to the default proxy group. This isn't true for the Word Automation service app. The New-SPWordConversionServiceApplication cmdlet has a "-Default" parameter that allows you to specify that it needs to get added. Unfortunately the SPWordAutomationServiceApp doesn't use this parameter currently.

#### Suggested solution to the issue
Add the possibility to specify that the service app proxy should be added to the default proxy group (only used during creation).

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
All

#### Version of the DSC module that was used
dev

### LINKED ISSUE #1271: [SPUserProfileSyncConnection] Resource does not update the sync connection if the UseSSL setting isn't in the desired state
#### Details of the scenario you tried and the problem that is occurring
The UseSSL setting is only used during creation of the connection. If the setting changes once the connection is already created, these settings aren't updated.

#### Suggested solution to the issue
Update the resource so it updates the UseSSL setting is updated.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2016/2019

#### Version of the DSC module that was used
dev

### LINKED ISSUE #1273: [SPQuotaTemplate] Updating Sandbox Code limits can throw an error
#### Details of the scenario you tried and the problem that is occurring
When you try to update an existing quota and have to lower the warning and max limits, it is possible that an error is thrown. For example:
Max limit=100
Warning limit=75

And the new values are:
Max limit=50
Warning limit=25

In this case the following error is thrown:
```PowerShell
Exception setting "UserCodeWarningLevel": "Specified argument was out of the range of valid values.
Parameter name: Maximum resource usage level must be an integer that is greater than the warning level."
```

#### Suggested solution to the issue
Check what the current warning limit is. If that is:
- higher than the new max limit, first update the max limit and then update the warning limit
- lower than the new max limit, first update the warning limit and then update the max limit

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SP2019

#### Version of the DSC module that was used
dev

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This PR fixes several bugs and updated the pipeline/build scripts.

#### This Pull Request (PR) fixes the following issues

- Fixes #1269 
- Fixes #1271 
- Fixes #1273 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Up for a review?

**Review by NikCharlebois — COMMENTED** [review]
Looks good. One item about a bak file that may not be required

> Reviewed 1 of 35 files at r2, 2 of 3 files at r4, 36 of 40 files at r5, 5 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274#-:-MQT5mdW7xlFywbvTReO:bmm673a)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[SharePointDsc/SharePointDsc.psd1.bak, line 0 at r6](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274#-MQT4_f4-X_G-fAR-rFJ:-MQT4_f57wzyRoi7cjzE:bs5hbqd) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/030a91ceb9180df9b83e226fdc0ad2688c01065c/SharePointDsc/SharePointDsc.psd1.bak#L0)):*
Do we need to keep that back file?

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274)* status: all files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[SharePointDsc/SharePointDsc.psd1.bak, line  at r6](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274#-MQT4_f4-X_G-fAR-rFJ:-MQTmbQU1Xd5hDPpLuN3:bugp28f) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/030a91ceb9180df9b83e226fdc0ad2688c01065c/SharePointDsc/SharePointDsc.psd1.bak#L)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Do we need to keep that back file?
</blockquote></details>

This has already been removed in the latest commit

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274)* status: all files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[SharePointDsc/SharePointDsc.psd1.bak, line  at r6](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1274#-MQT4_f4-X_G-fAR-rFJ:-MQTmj781chIrUujcXCP:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/030a91ceb9180df9b83e226fdc0ad2688c01065c/SharePointDsc/SharePointDsc.psd1.bak#L)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

This has already been removed in the latest commit
</blockquote></details>

Done.

**Pull request merged**
