### PR TITLE
[SPCertificate/SPWebApplication/SPWebApplicationExtension] New and updated resources to support certificate management

### LINKED ISSUE #1363: [SPCertificate] New resource to manage certificates in SPSE Certificate Management
### Description
In SPSE a new Certificate Management feature is implemented. This resource should be able to import certificates to this new store.

### Proposed properties

| Type | Data type | Name | Values |
| --- | --- | --- | --- |
| Key | String | CertificateFilePath | |
| Write | PSCredential | CertificatePassword | |
| Write | String | Store | EndEntity,Intermediate,Pending,Root | |
| Write | Boolean | Exportable | |
| Write | String | Ensure | Present,Absent | |

### LINKED ISSUE #1364: [SPWebApplication] Add ability to manage assigned certificate to the web app
#### Details of the scenario you tried and the problem that is occurring
SPSE adds the ability to manage SSL certificates from SharePoint. Issue #1363 is for managing certificates in the store. But SPWebApplication should also be updated to allow applying a certificate to a web application.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SPWebApplication HostNameSiteCollectionWebApp
{
    Name                   = "SharePoint Sites"
    ApplicationPool        = "SharePoint Sites"
    ApplicationPoolAccount = "CONTOSO\svcSPWebApp"
    AllowAnonymous         = $false
    DatabaseName           = "SP_Content_01"
    DatabaseServer         = "SQL.contoso.local\SQLINSTANCE"
    WebAppUrl              = "http://example.contoso.local"
    Port                   = 80
    Ensure                 = "Present"
    CertificateThumbprint  = "abcdefabcdef"
}
```

### LINKED ISSUE #1365: Problem with version 5.0 of resource MSFT_SPWebApplication.psm1
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE: MSFT_SPWebApplication.psm1: hardcoded url for WA
   
    ISSUE DESCRIPTION (this template):
    I get an error when configurring a farm that it can't find web application on url https://root.portal.politie.local
    I searched the code and found this on line 110 in MSFT_SPWebApplication.psm1
    $wa = Get-SPWebApplication https://root.portal.politie.local
    I have some other issues when running the script but hard to say if this one is the root cause

#### Verbose logs showing the problem

Cannot find an SPWebApplication object with Name, Id, or Url: https://root.portal.politie.local.
    + CategoryInfo          : InvalidData: (Microsoft.Share...tWebApplication:) [], CimException
    + FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SpCmdletGetWebApplication
    + PSComputerName        : swazserver00.c0nt0s00.local

#### Version of the DSC module that was used
Version 5.0

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This PR adds a new SPCertificate resource to import certificates to the new Certificate Management feature in SharePoint Subscription Edition and updates SPWebApplication/SPWebApplicationExtension to support the configuration of certificates.

#### This Pull Request (PR) fixes the following issues

- Fixes #1363 
- Fixes #1364 
- Fixes #1365 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362)

### CODE REVIEW

**Review by NikCharlebois — COMMENTED** [review]
Small update needed to the Ensure property of the Schema

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-:-MqPY4G1CzLDdXvesCbH:bsapc6m)* status: all files reviewed, 1 unresolved discussion (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPCertificate/MSFT_SPCertificate.schema.mof, line 8 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-MqPXvWL6_U_KNoLC2HW:-MqPXvWL6_U_KNoLC2HX:bk2hwfy) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/e0f95b47d1a2d1c32f022fe45e587482304d7dc9/SharePointDsc/DSCResources/MSFT_SPCertificate/MSFT_SPCertificate.schema.mof#L8)):*
> ```
>     [Write, Description("Specifies the store in which the certificate should be placed"), ValueMap{"EndEntity","Intermediate","Pending","Root"}, Values{"EndEntity","Intermediate","Pending","Root"}] String Store;
>     [Write, Description("Specifies if the certificate should be exportable after import")] Boolean Exportable;
>     [Write, Description("Present ensures service app exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
> ```

I think this definition needs updating

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPCertificate/MSFT_SPCertificate.schema.mof, line 8 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-MqPXvWL6_U_KNoLC2HW:-MqPYgcV2bH1moW8aHul:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/e0f95b47d1a2d1c32f022fe45e587482304d7dc9/SharePointDsc/DSCResources/MSFT_SPCertificate/MSFT_SPCertificate.schema.mof#L8)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I think this definition needs updating
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-:-MqPZ-us7cxXBGQTjxRQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Comment by brianlala** [comment]
A couple of suggestions based on my recent testing:

- CertificatePassword should not be required; if a cert was secured using an AD account, then if the same account is running the import, no password would be needed and sure enough Import-SPCertificate doesn't enforce one either
- Consider implementing the Replace parameter, and default to $false. This is useful when e.g. you want to import the same cert to multiple stores (think self-signed certs that need to be both in the Root as well as in EndEntity). Otherwise the resource just overwrites the existing store and you either end up in EndEntity but not in Root (and not trusted by the local web browser) or in Root but not EndEntity (and thus not usable by IIS)

**Comment by brianlala** [comment]
> Suggestion based on my recent testing:
> 
> * Consider implementing the Replace parameter, and default to $false. This is useful when e.g. you want to import the same cert to multiple stores (think self-signed certs that need to be both in the Root as well as in EndEntity). Otherwise the resource just overwrites the existing store and you either end up in EndEntity but not in Root (and not trusted by the local web browser) or in Root but not EndEntity (and thus not usable by IIS)

On second thought I'm not sure if this would do the trick. DSC replaces the existing cert, but I can manually run Import-SPCertificate using the same cert, but to a different store.

**Comment by ykuijs** [comment]
@brianlala There are two types of certificate packages:

1. Just the public certificate (CER file)
2. The public and private certificate (PFX file)

Usually the certificates imported to the EndEntity store are the ones with both the public and private keys, so IIS is able to encrypt all ingoing and outgoing traffic. You can only select these certificates on a web application.

However the certificate imported into the Root or Intermediate store just has to be the public certificate, so Windows is able to validate the certificate chain. It does not need the private key for that.

During development I did not test what happens if you try to import a PFX file in multiple stores (I just did and that is indeed possible), but I did test importing both a CER and PFX file. So at the moment this resource is able to import the CER file to one store and the PFX file into the EndEntity store. I also tested what happens if you import one package to a store and then the other (first CER and then PFX and the other way around):

- First import CER: The item does not have a private key, after importing the PFX the private key is added.
- First import PFX: The item already has a private key, so after importing the CER nothing happens.

This means the scenario you are describing with using a self signed certificate is possible, you just have to use a PFX and a CER file for that.

Does this make sense?

**Comment by ykuijs** [comment]
> > Suggestion based on my recent testing:
> > 
> > * Consider implementing the Replace parameter, and default to $false. This is useful when e.g. you want to import the same cert to multiple stores (think self-signed certs that need to be both in the Root as well as in EndEntity). Otherwise the resource just overwrites the existing store and you either end up in EndEntity but not in Root (and not trusted by the local web browser) or in Root but not EndEntity (and thus not usable by IIS)
> 
> On second thought I'm not sure if this would do the trick. DSC replaces the existing cert, but I can manually run Import-SPCertificate using the same cert, but to a different store.

@brianlala My thought was that SPCertificate would be used to manage certificates in the Certificate Store and SPWebApplication would manage which certificate was applied to the web application. So you would first have to use SPCertificate to import the new certificate to the store, after which you can use SPWebApplication to apply that new certificate to the web application.

What is your idea about this?

**Comment by brianlala** [comment]
> > > Suggestion based on my recent testing:
> > > 
> > > * Consider implementing the Replace parameter, and default to $false. This is useful when e.g. you want to import the same cert to multiple stores (think self-signed certs that need to be both in the Root as well as in EndEntity). Otherwise the resource just overwrites the existing store and you either end up in EndEntity but not in Root (and not trusted by the local web browser) or in Root but not EndEntity (and thus not usable by IIS)
> > 
> > 
> > On second thought I'm not sure if this would do the trick. DSC replaces the existing cert, but I can manually run Import-SPCertificate using the same cert, but to a different store.
> 
> @brianlala My thought was that SPCertificate would be used to manage certificates in the Certificate Store and SPWebApplication would manage which certificate was applied to the web application. So you would first have to use SPCertificate to import the new certificate to the store, after which you can use SPWebApplication to apply that new certificate to the web application.
> 
> What is your idea about this?

That's exactly what I was thinking too, and I was only referencing the import of certs in this thread, not applying them to web apps (as I realize that's forthcoming).

**Comment by brianlala** [comment]
> @brianlala There are two types of certificate packages:
> 
> 1. Just the public certificate (CER file)
> 2. The public and private certificate (PFX file)
> 
> Usually the certificates imported to the EndEntity store are the ones with both the public and private keys, so IIS is able to encrypt all ingoing and outgoing traffic. You can only select these certificates on a web application.
> 
> However the certificate imported into the Root or Intermediate store just has to be the public certificate, so Windows is able to validate the certificate chain. It does not need the private key for that.
> 
> During development I did not test what happens if you try to import a PFX file in multiple stores (I just did and that is indeed possible), but I did test importing both a CER and PFX file. So at the moment this resource is able to import the CER file to one store and the PFX file into the EndEntity store. I also tested what happens if you import one package to a store and then the other (first CER and then PFX and the other way around):
> 
> * First import CER: The item does not have a private key, after importing the PFX the private key is added.
> * First import PFX: The item already has a private key, so after importing the CER nothing happens.
> 
> This means the scenario you are describing with using a self signed certificate is possible, you just have to use a PFX and a CER file for that.
> 
> Does this make sense?

Yes, this makes sense. And importing both .cer for root and .pfx for EndEntity is probably the best way to go. I was just being lazy before by using .pfx for both. And really this shouldn't be a concern with production environments where we wouldn't normally be using self-signed anyhow.

**Review by NikCharlebois — COMMENTED** [review]
Few instances of the same comment to answer to

> Reviewed 1 of 1 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-:-MqxvVyR2BNm5Ij7HS7s:b-yh7g0m)* status: all files reviewed, 4 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1, line 87 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-MqxudYiEJoIZGRyo3Tv:-MqxudYiEJoIZGRyo3Tw:b-m3bqvy) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/686ea8019aab55d58478d85c0c8e35fcee6fb79b/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L87)):*
> ```PowerShell
>         ($osVersion.Major -ne 10 -or $osVersion.Build -ne 20348))
>     {
>         Write-Verbose ("You cannot specify the AllowLegacyEncryption parameter when using " + `
> ```

Isn't the if statement checking for OS version, but message calling out an invalid SP version. Which is it?
___
*[SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1, line 284 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-Mqxv0T_98DPiDNwP5wr:-Mqxv0T_98DPiDNwP5ws:bbxgkzp) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/686ea8019aab55d58478d85c0c8e35fcee6fb79b/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L284)):*
> ```PowerShell
>         ($osVersion.Major -ne 10 -or $osVersion.Build -ne 20348))
>     {
>         $message = ("You cannot specify the AllowLegacyEncryption parameter when using " + `
> ```

Same comment as above
___
*[SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 64 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-MqxvFl--8Kz6lXpBfaY:-MqxvFl--8Kz6lXpBfaZ:b-ya81ng) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/686ea8019aab55d58478d85c0c8e35fcee6fb79b/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L64)):*
> ```PowerShell
>         ($osVersion.Major -ne 10 -or $osVersion.Build -ne 20348))
>     {
>         Write-Verbose ("You cannot specify the AllowLegacyEncryption parameter when using " + `
> ```

Same as above
___
*[SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1, line 231 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-MqxvKk_2XU8dWl2ZjF5:-MqxvKk_2XU8dWl2ZjF6:bb73xfv) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/686ea8019aab55d58478d85c0c8e35fcee6fb79b/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1#L231)):*
> ```PowerShell
>         ($osVersion.Major -ne 10 -or $osVersion.Build -ne 20348))
>     {
>         $message = ("You cannot specify the AllowLegacyEncryption parameter when using " + `
> ```

Same

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362#-:-Mqy30EmBwnyv8VxrosP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Pull request merged**
