### PR TITLE
Wiki Resource overview: Formatting issue with credssp column

### PR DESCRIPTION
**Pull request by bartvermeersch**
Removed extra empty cell.

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1405)

### CODE REVIEW

**Comment by ykuijs** [comment]
Hi @bartvermeersch, good spot! Could you do me favor though: The pipeline is failing because this PR does not contain an updated changelog, which is required so all changes are properly documented.

Could you please add the following lines to the Fixed block in the Unreleased section (at the top of the list):
```
- SharePointDsc
  - Fixed incorrect table formatting in the resource table of the Wiki
```

**Comment by bartvermeersch** [comment]
I'm not sure where to add it ...

Is it in a file or my initial comment? thanks

**Comment by ykuijs** [comment]
The repository contains a Changelog.md file:
https://github.com/dsccommunity/SharePointDsc/blob/master/CHANGELOG.md

Then add it here:
image

**Review by ykuijs — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1405)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bartvermeersch)

**Pull request merged**
