### PR TITLE
SPFarm: Added ApplicationCredentialKey

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description
Added ApplicationCredentialKey parameter for SP2019

#### This Pull Request (PR) fixes the following issues
None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1147)

### CODE REVIEW

**Comment by ykuijs** [comment]
Because of the new CI system, I had to re-target this release to master. Can you please do a pull from master and resolve any conflicts?

**Comment by jensotto** [comment]
I'm unable to merge/rebase this due to a rename of the tests folder forcing git to add a new version of the SPFarm tests file. I'm not sure how to fix that.

**Comment by jensotto** [comment]
@ykuijs updated PR as requested

**Comment by jensotto** [comment]
I don't see any way to prevent this. This is something that needs to be specified on each server, and there is no way to extract current vaule for either current server or any remote server. The only approach I can think of is to use one server to set this value remotely on all other servers in the farm, but if I remember correctly this is something that is specified in this project that should be avoided.

**Comment by jensotto** [comment]
No problem. I just didn't notice that when coding.

**Comment by ykuijs** [comment]
Merging as soon as the tests complete

**Pull request merged**
