### PR TITLE
Update SPExcelServiceApp Documentation and exception

### LINKED ISSUE #1162: SPExcelServiceApp - Add Deprecation details to Documentation
The documentation for SPExcelServiceApp should be updated to include the following notation, as implemented in the SharePointDsc and output from the DSC execution:

Only SharePoint 2013 is 
supported to deploy Excel Services service applications via DSC, as SharePoint 2016 and SharePoint 2019 are deprecated this service. See 
https://technet.microsoft.com/en-us/library/mt346112(v=office.16).aspx for more info.

Excel

### LINKED ISSUE #1169: SPInstallPrereqs:  SQLNCli Required in 2019
Installation of the SP Pre Requisites in offline mode for SharePoint 2019 throws error indicating that SQLNCli is required:

image

The current [SPInstallPrereqs Documentation](https://github.com/dsccommunity/SharePointDsc/wiki/SPInstallPrereqs) states that this parameter is for 2013 and 2016 only.

### PR DESCRIPTION
**Pull request by ruandersMSFT**
#### Pull Request (PR) description

Update to SPExcelServiceApp Documentation + exception grammar.

#### This Pull Request (PR) fixes the following issues

- Fixes #1162 - SPExcelServiceApp - Add Deprecation details to Documentation
- Fixes #1169 - SPInstallPrereqs:  Documentation Update 2019 Offline Parameters

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1163)

### CODE REVIEW

**Comment by ykuijs** [comment]
Please update from Master to pull in the fixes for the failing Pester test

**Comment by ykuijs** [comment]
You just need to add a newline at the end of the Readme file you updated (we require that markdown files end with an empty line).

**Comment by ruandersMSFT** [comment]
@ykuijs Not sure if I need to do something to clear the "1 discussion left", ready for merge.

**Comment by ykuijs** [comment]
Had to update this PR with changes from master. Will merge as soon as all tests have completed successfully.

**Pull request merged**
