### PR TITLE
More SPSE improvements

### LINKED ISSUE #1357: Office Online Server Supression settings
### Description
For OOS you can configure extensions that should not be handled by OOS. SharePointDsc currently does not have the possibility to manage these settings. 

*-WOPISupressionSettings cmdlets exist: https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spwopisuppressionsetting

Would it be possible to create a resource for this?

### Proposed properties
Extension: For example, PDF
Action: View / Edit / EmbedView
Ensure: Absent / Present

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This PR adds several more SharePoint Server Subscription Edition improvements:
- New Certificate Settings resource
- Added SPSE unit tests to the pipeline
- Made all unit tests compatible with SPSE
- Several minor fixes that were discovered during unit testing

It also adds a new OOS resource, that was recently requested.

#### This Pull Request (PR) fixes the following issues

- Fixes #1357 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358)

### CODE REVIEW

**Review by NikCharlebois — COMMENTED** [review]
Just one clarification for a readme.md file

> Reviewed 1 of 17 files at r2, 34 of 34 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358#-:-MoL0yx6EfEe8e5o7kBf:b-jie29s)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois and @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerSupressionSettings/readme.md, line 10 at r6](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358#-MoL0JW76e8X7259tfkS:-MoL0JW76e8X7259tfkT:b-l3pa3b) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2fa5685a8ac2aeba0b878d0dcaab61d2ebc6d8b2/SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerSupressionSettings/readme.md#L10)):*
> ```Markdown
> which extensions should Office Online Server not be used to open the file.
> 
> The default value for the Ensure parameter is Present. When not specifying this
> ```

Is this sentence correct? What zone are we referring to here?

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358)* status: 33 of 35 files reviewed, 1 unresolved discussion (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerSupressionSettings/readme.md, line 10 at r6](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358#-MoL0JW76e8X7259tfkS:-MoL2krzBW2yovd0nmVy:b-763ud2) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2fa5685a8ac2aeba0b878d0dcaab61d2ebc6d8b2/SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerSupressionSettings/readme.md#L10)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Is this sentence correct? What zone are we referring to here?
</blockquote></details>

Good spot, copy paste issue. Have corrected the text.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358#-:-MoL39e61c-v6zawKKhp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Review by NikCharlebois — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1358#-:-MoTjwEU60BZUOuTwLrx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Comment by shurick81** [comment]
Is there a link to the new version of the module?
We are using https://techcommunity.microsoft.com/gxcuf89792/attachments/gxcuf89792/SharePointDsc/43/1/SharePointDsc_v5.0_SPSE-PublicPreview.zip but after upgrading to SP SE RTM it stopped working properly with installing prerequisites.

**Comment by ykuijs** [comment]
Hi @shurick81, you can download the v5.0 branch and then run `.\build.ps1 -Tasks Build`. That will create a new local version of the module in the newly created output folder in the project folder, which you can use.

One remark: The Build process will try to use gitversion to determine the version number that should be used. If you don't have that installed on your machine, you might end up with a module version 0.0.1. It works just as fine, but only showing an incorrect build number :wink:

**Pull request merged**
