### PR TITLE
MSFT_SPSecurityTokenServiceConfig: Added properties FormsTokenLifetime, WindowsTokenLifetime and LogonTokenCacheExpirationWindow

### PR DESCRIPTION
**Pull request by ThomasLie**
#### Pull Request (PR) description

This resource is also able to set the properties FormsTokenLifetime, WindowsTokenLifetime and LogonTokenCacheExpirationWindow.
It checks for values leading to “The context has expired and can no longer be used.” errors.
The value for LogonTokenCacheExpirationWindow must be higher than the values for FormsTokenLifetime and WindowsTokenLifetime,
it will return an error if not.

#### This Pull Request (PR) fixes the following issues

- Fixes 1302

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307)

### CODE REVIEW

**Review by ykuijs — CHANGES_REQUESTED** [review]
Great first draft. I have added some comments. Also please add a entry in the Changelog to track all implemented changes.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-:-MXggzeSAPeRURyLwQoN:b-r5km5r)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @ThomasLie)

___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 36 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgZ0REE1zs40A4h6kM:-MXgZ0REE1zs40A4h6kN:bx5b31) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L36)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.Int32]
> ```

Please update to System.Uint32, also for the Set and Test methods
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 40 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgYxxI-COb8Wd7QrtC:-MXgYxxI-COb8Wd7QrtD:bx5b31) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L40)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.Int32]
> ```

Please update to System.Uint32, also for the Set and Test methods
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 44 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgZ-S-Bt52XYeHhoQb:-MXgZ-S-Bt52XYeHhoQc:bx5b31) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L44)):*
> ```PowerShell
> 
>         [Parameter()]
>         [System.Int32]
> ```

Please update to System.Uint32, also for the Set and Test methods
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 69 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgeceD7bLq7Y0THZQQ:-MXgZZS7EMvQy_D5k8hf:b-upna71) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L69)):*
> ```PowerShell
>         {
>             # Converting timespan values back to int32
>             [Int32]$FormsTokenLifetime = $config.FormsTokenLifetime
> ```

This conversion does not work and results in an error:
```
PS C:\> [int32](Get-SPSecurityTokenServiceConfig).FormsTokenLifetime
Cannot convert the "10:00:00" value of type "System.TimeSpan" to type "System.Int32".
At line:1 char:1
+ [int32](Get-SPSecurityTokenServiceConfig).FormsTokenLifetime
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException

```

Please use:
`$FormsTokenLifetime = $config.FormsTokenLifetime.TotalMinutes`
And since the check below this section will be moved outside of the Invoke block, we can directly use the $config.FormsTokenLifetime.TotalMinutes in the return hashtable.

Same of course for the other two values.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 73 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXg_M-458gIEKm-YhUy:-MXg_M-458gIEKm-YhUz:bz86esh) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L73)):*
> ```PowerShell
>             [Int32]$LogonTokenCacheExpirationWindow = $config.LogonTokenCacheExpirationWindow
>             
>             if ( ($params.LogonTokenCacheExpirationWindow -le $FormsTokenLifetime) -or ($params.LogonTokenCacheExpirationWindow -le $WindowsTokenLifetime) )
> ```

Please move this check just before the Invoke-SPDscCommand section. Checking parameters should be done as early as possible and not inside of the Invoke-SPDscCommand block (which is only taking up extra CPU cycles).

Also, you are checking against the live settings, please check the parameter against the values specified in the config and make sure you check if the parameter is actually specified before you are going to check it:

```PowerShell
if ($PSBoundParameters.ContainsKey("LogonTokenCacheExpirationWindow") -eq $true -and `
    $PSBoundParameters.ContainsKey("WindowsTokenLifetime") -eq $true)
{
    if ($LogonTokenCacheExpirationWindow -le $WindowsTokenLifetime)
   {
      [THROW ERROR HERE]
   }
}
```
And the same for the FormsTokenLifetime parameter as well.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 109 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgfHMg9rqWqJzMJPEz:-MXgfHMg9rqWqJzMJPF-:b5mmw2e) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L109)):*
> ```PowerShell
>             AllowOAuthOverHttp              = $config.AllowOAuthOverHttp
>             AllowMetadataOverHttp           = $config.AllowMetadataOverHttp
>             FormsTokenLifetime              = $FormsTokenLifetime
> ```

This is where we can use the $config.FormsTokenLifetime.TotalMinutes
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 222 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgg4rOD-lSfOJvwFbZ:-MXgg4rOD-lSfOJvwFb_:b-6d5ev9) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L222)):*
> ```PowerShell
>         if ($params.ContainsKey("LogonTokenCacheExpirationWindow"))
>         {
>             if ($params.ContainsKey("WindowsTokenLifetime") -or $params.ContainsKey("FormsTokenLifetime"))
> ```

I like the check you added in the Get method to check against the already configured value. So I would change this login to:
If the LogonTokenCacheExpirationWindow parameter is specified, but the WindowsTokenLifetime parameter isn't: Check the value of LogonTokenCacheExpirationWindow against the already configured value of WindowsTokenLifetime. And if that is larger, throw an exception!

And the same for FormsTokenLifetime of course.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 224 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXgfsQe8883suJrgf_f:-MXgfsQe8883suJrgf_g:b79v3dw) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L224)):*
> ```PowerShell
>             if ($params.ContainsKey("WindowsTokenLifetime") -or $params.ContainsKey("FormsTokenLifetime"))
>             {
>                 if ( ($params.LogonTokenCacheExpirationWindow -le $params.WindowsTokenLifetime) -or ($params.LogonTokenCacheExpirationWindow -le $params.FormsTokenLifetime) )
> ```

Just as with the Get method, please move this check outside of the Invoke block.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.schema.mof, line 10 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXggbxq4X4zp531nXuU:-MXggbxq4X4zp531nXuV:b-g3vrpj) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.schema.mof#L10)):*
> ```
>     [Write, Description("True set the security token service to allow OAuth over HTTP")] Boolean AllowOAuthOverHttp;
>     [Write, Description("True set the security token service to allow metadata exchange over HTTP")] Boolean AllowMetadataOverHttp;
>     [Write, Description("Timespan in minutes to set FormsTokenLifetime")] Int32 FormsTokenLifetime;
> ```

Int32 isn't an allowed type in MOF schemas, please update to Uint32: https://docs.microsoft.com/en-us/windows/win32/wmisdk/numbers

Same for other two parameters of course.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/readme.md, line 11 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXggoMn-vOzIug-FHjU:-MXggoMn-vOzIug-FHjV:buv2bcy) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/799a20bca084df560d37b6887e2a979b682b642c/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/readme.md#L11)):*
> ```Markdown
> 
> This resource is also able to set the properties FormsTokenLifetime, WindowsTokenLifetime and LogonTokenCacheExpirationWindow.
> It checks for values leading to �The context has expired and can no longer be used.� errors.
> ```

There is a strange character where quotes should be. Can you please check if the correct characters are used here?

**Review by ykuijs — CHANGES_REQUESTED** [review]
Great move forward, a few more comments.

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-:-MXl0wfH22aaQWlH8i3U:b-xn49ew)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @ThomasLie)

___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 60 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkwCNp9fSvsbS9d7oU:-MXkwCNp9fSvsbS9d7oV:b-mo6j4r) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L60)):*
> ```PowerShell
>         $PSBoundParameters.ContainsKey("WindowsTokenLifetime") -eq $true)
>     {
>         if ($PSBoundParameters.LogonTokenCacheExpirationWindow -le $PSBoundParameters.WindowsTokenLifetime)
> ```

Shouldn't this be -ge instead of -le?? The LogonTokenCacheExpirationWindow should be lower than the TokenLifetimes, so we should check if the specified value is greater than or equal.

Same for the FormsTokenLifetime check.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 62 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkvKek1RZVw1G1FxAK:-MXkvKek1RZVw1G1FxAL:bho184x) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L62)):*
> ```PowerShell
>         if ($PSBoundParameters.LogonTokenCacheExpirationWindow -le $PSBoundParameters.WindowsTokenLifetime)
>         {
>             $message = ("Setting LogonTokenCacheExpirationWindow to a value lower or equal as WindowsTokenLifetime ist not supported. " + `
> ```

Typo in the word "is", does not need the additional "t". This is true for all error messages.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 87 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkv6sm8oN-kIhJMpFP:-MXkv6sm8oN-kIhJMpFQ:b6wuhuj) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L87)):*
> ```PowerShell
>     }
> 
>     Write-Verbose -Message "Getting Security Token Service Configuration"
> ```

This should be the first line in the function, so with troubleshooting you can quickly see you have entered the Get method ;-)
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 96 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkuIMGDbDp_84WnKme:-MXkuIMGDbDp_84WnKmf:bgss51o) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L96)):*
> ```PowerShell
>         $config = Get-SPSecurityTokenServiceConfig
> 
>         if ($null -ne $config)
> ```

I think we can remove the whole If section here. This will all be checked in the Set method.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 211 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkvk83802rtPCSifcD:-MXkvk83802rtPCSifcE:b-j2883f) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L211)):*
> ```PowerShell
>         $PSBoundParameters.ContainsKey("WindowsTokenLifetime") -eq $true)
>     {
>         if ($PSBoundParameters.LogonTokenCacheExpirationWindow -le $PSBoundParameters.WindowsTokenLifetime)
> ```

Shouldn't this be -ge instead of -le?? The LogonTokenCacheExpirationWindow should be lower than the TokenLifetimes, so we should check if the specified value is greater than or equal.

Same for the FormsTokenLifetime check.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 213 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkyGLs7q05yv1sE0sY:-MXkyGLs7q05yv1sE0sZ:bra3eyi) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L213)):*
> ```PowerShell
>         if ($PSBoundParameters.LogonTokenCacheExpirationWindow -le $PSBoundParameters.WindowsTokenLifetime)
>         {
>             $message = ("Setting LogonTokenCacheExpirationWindow to a value lower or equal as WindowsTokenLifetime ist not supported. " + `
> ```

This message should be update to match the previous comment.
___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 277 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXkwibqEbLkCeFNXK3n:-MXkwibqEbLkCeFNXK3o:b6yslib) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/a9e800a38b39a70635e96c2214083e90bd1f2d3b/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L277)):*
> ```PowerShell
>         if ($params.ContainsKey("LogonTokenCacheExpirationWindow"))
>         {
>             if (!($params.ContainsKey("WindowsTokenLifetime")) -and ($params.LogonTokenCacheExpirationWindow -le $config.WindowsTokenLifetime.TotalMinutes))
> ```

Please use the "-not" operator instead of "!".

Shouldn't this be -ge instead of -le?? The LogonTokenCacheExpirationWindow should be lower than the TokenLifetimes, so we should check if the specified value is greater than or equal.

Same for the FormsTokenLifetime check.

**Comment by ThomasLie** [comment]
Updated checks for LogonTokenCacheExpirationWindow values:

`if ($PSBoundParameters.ContainsKey("LogonTokenCacheExpirationWindow") -eq $true -and `
        $PSBoundParameters.ContainsKey("WindowsTokenLifetime") -eq $true)
    {
        if ($PSBoundParameters.LogonTokenCacheExpirationWindow -ge $PSBoundParameters.WindowsTokenLifetime)
        {
            $message = ("Setting LogonTokenCacheExpirationWindow to a value higher or equal as WindowsTokenLifetime is not supported. " + `
                    "Please set LogonTokenCacheExpirationWindow to value lower as WindowsTokenLifetime")
            Add-SPDscEvent -Message $message `
                -EntryType 'Error' `
                -EventID 100 `
                -Source $MyInvocation.MyCommand.Source
            throw $message
        }
    }

    if ($PSBoundParameters.ContainsKey("LogonTokenCacheExpirationWindow") -eq $true -and `
        $PSBoundParameters.ContainsKey("FormsTokenLifetime") -eq $true)
    {
        if ($PSBoundParameters.LogonTokenCacheExpirationWindow -ge $PSBoundParameters.FormsTokenLifetime)
        {
            $message = ("Setting LogonTokenCacheExpirationWindow to a value higher or equal as FormsTokenLifetime is not supported. " + `
                    "Please set LogonTokenCacheExpirationWindow to value lower as FormsTokenLifetime")
            Add-SPDscEvent -Message $message `
                -EntryType 'Error' `
                -EventID 100 `
                -Source $MyInvocation.MyCommand.Source
            throw $message
        }
    }`

**Review by ykuijs — CHANGES_REQUESTED** [review]
One last update you missed ;-)

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-:-MXnPnYj28cz7ir6A1TM:b6brn7j)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ThomasLie)

___
*[SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1, line 77 at r3](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-MXnPIEu7R6sRtQ3nKgZ:-MXnPIEu7R6sRtQ3nKg_:ba303m8) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/38e760dec63ff3338c1c89a0e613e2af55bc9651/SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1#L77)):*
> ```PowerShell
>         $PSBoundParameters.ContainsKey("FormsTokenLifetime") -eq $true)
>     {
>         if ($PSBoundParameters.LogonTokenCacheExpirationWindow -le $PSBoundParameters.FormsTokenLifetime)
> ```

Same issue with ge instead of le here

**Review by ykuijs — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThomasLie)

**Review by ykuijs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307#-:-MXqBOgJCQ44Uknfu4SE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ThomasLie)

**Comment by ykuijs** [comment]
@ThomasLie I have merged this PR. Thanks for your contribution!

**Comment by ThomasLie** [comment]
Hi Yorick,

you‘re welcome...

Next one is fixing psconfig...

We‘re currently on a promising way, will keep you updated...

Btw, another German client has the same issue and opened a case...

Mit freundlichen Grüßen

Thomas Lieftüchter

Lieftüchter IT-Consulting & Hausverwaltung GbR
Römerweg 10a
63303 Dreieich - Germany
Fon: +49 171.2625166
Email: ***@***.***
Web: http://www.lieftuechter.com/TL

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
________________________________
Von: Yorick Kuijs ***@***.***>
Gesendet: Friday, April 9, 2021 8:50:25 PM
An: dsccommunity/SharePointDsc ***@***.***>
Cc: Thomas Lieftüchter ***@***.***>; Mention ***@***.***>
Betreff: Re: [dsccommunity/SharePointDsc] MSFT_SPSecurityTokenServiceConfig: Added properties FormsTokenLifetime, WindowsTokenLifetime and LogonTokenCacheExpirationWindow (#1307)


@ThomasLie<https://github.com/ThomasLie> I have merged this PR. Thanks for your contribution!

**Pull request merged**
