### PR TITLE
SharePointDsc: Fix code coverage in pipeline

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description

- SharePointDsc
  - Fixed code coverage in pipeline.

#### This Pull Request (PR) fixes the following issues

None.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1308)

### CODE REVIEW

**Comment by johlju** [comment]
@ykuijs this PR is to fix breaking changes that will be introduced once we release latest Sampler.

**Comment by johlju** [comment]
Hmm. For some reason all strings were changed. Will be back with a new commit.

**Comment by johlju** [comment]
Now it is ready.

**Review by ykuijs — CHANGES_REQUESTED** [review]
@johlju One question about this PR

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1308#-:-MXmpyN0AdKUAxrNnZ-B:b-zcgtwe)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[azure-pipelines.yml, line 241 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1308#-MXmp_t4Cun7tvnMtdx1:-MXmp_t4Cun7tvnMtdx2:b-9ck7zy) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/8efd16a40ffd20c9d3881f80914b7064f3ee6b80/azure-pipelines.yml#L241)):*
> ```YAML
>               buildType: 'current'
>               artifactName: 'CodeCoverage_2019'
>               targetPath: '$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/CodeCov2019'
> ```

Is there a specific reason you left the $(Build.SourcesDirectory) parameter here and the two changed lines above, but removed it in the next changed line?

**Comment by johlju** [comment]
@ykuijs once approved, hold off merging until I have a chance to look at the xml that is generated. I might need to revert the change I did in codecov.yml since the new Convert function is not needed (for class-based resources).

**Review by ykuijs — APPROVED** [review]
I don't mind if we are going to use one or the other, as long as it works :smile: Just noticed that the two changes were different, but in the end they should point to the same location.

:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1308#-:-MXn-o-f0-g4hOe4nIlc:bjtjmlh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Comment by johlju** [comment]
This is ready to be merged.

The codecov.yml change needed to be reverted, also saw that it didn't was correct tfor this repo since this repo does not use 'source', but 'SharePointDsc' as the source folder. I changed accordingly, so Codecov.io should work better with this change.

For your information:

Azure Code Coverage will work as bad as before since Azure Code Coverage expects the full relative path (from `pathToSources` in azure-piplines.yml) to be in the `<sourcefile>` element. Pester does not do this. Codecov.io is smarter and builds the relative path from the `<package>` and `<sourcefile>` element. But since pester generates the module version in the `<package>` element we need to switch that out to the correct name, in this case `SharePointDsc`.

The new task _Convert\_Pester\_Coverage_ will fix all this, but only for class-based resources and module built using the ModuleBuilder's pattern (Public, Private, Classes, Enum). MOF-resource will still be an issue until Pester is fixed.

Example DnsServerDsc, can see the MOF does not show content in the source files, but class-based resources does: https://dev.azure.com/dsccommunity/DnsServerDsc/_build/results?buildId=4325&view=codecoverage-tab

But both works for codecov.io: https://app.codecov.io/gh/dsccommunity/DnsServerDsc/compare/253/tree/source

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1308#-:-MXq5gZRES1xdzonWG4P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
