### PR TITLE
SPWebAppPeoplePickerSettings: Adds support for parameter CustomFilter and ShortDomainName

### LINKED ISSUE #1393: [SPWebAppPeoplePickerSettings] SearchActiveDirectoryDomains - CustomFilter
The Ressource SPWebAppPeoplePickerSettings does not support the following Properties for SearchActiveDirectoryDomains
* [CustomFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.sppeoplepickersearchactivedirectorydomain.customfilter?view=sharepoint-server#microsoft-sharepoint-administration-sppeoplepickersearchactivedirectorydomain-customfilter)
* [ShortDomainName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.administration.sppeoplepickersearchactivedirectorydomain.shortdomainname?view=sharepoint-server#microsoft-sharepoint-administration-sppeoplepickersearchactivedirectorydomain-shortdomainname)

The Parameters of `MSFT_SPWebAppPPSearchDomain` should be extended by:
| Parameter       | Attribute | DataType | Description                                                | Allowed Values |
|-----------------|-----------|----------|------------------------------------------------------------|----------------|
| CustomFilter    | Write     | String   | Sets a customized query filter to send to Active Directory |                |
| ShortDomainName | Write     | String   | NetBIOS name of the domain or forest                       |                |

I'd like to create a pull request with the needed changes.

I've checked the current code and the Set function only seems to add a `SPPeoplePickerSearchActiveDirectoryDomain` if it can not find one with the given `DomainName` and `IsForest` Property.
As far as i can see the [current implementation](https://github.com/dsccommunity/SharePointDsc/blob/fe2111d3c911e2b5ddd7f14855f1a17c32ff0047/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1#L184) would not change the `AccessAccount` Property of an existing `SPPeoplePickerSearchActiveDirectoryDomain`.
Currently the existing code would only apply a change, if the required parameters `FQDN` and `IsForest` change, but not the optional ones.

Since i'd also need that for the other optional parameters - is there another ressource which is a good code example?

### PR DESCRIPTION
**Pull request by ChristophHannappel**
### Added

  - SPWebAppPeoplePickerSettings
    - Added the CustomFilter parameter to the resource
    - Added the ShortDomainName parameter to the resource

### Fixed

- SPWebAppPeoplePickerSettings
  - Fixed an issue where the Set method would not update a non mandatory parameter on an existing SPWebAppPPSearchDomain
  - Expanded the unit tests for AccessAcount

#### This Pull Request (PR) fixes the following issues

- Fixes #1393

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396)

### CODE REVIEW

**Comment by ChristophHannappel** [comment]
I think the CodeCov has some false postives.
https://github.com/dsccommunity/SharePointDsc/pull/1396/files#annotation_2946439513
https://github.com/dsccommunity/SharePointDsc/pull/1396/files#annotation_2946439514
https://github.com/dsccommunity/SharePointDsc/pull/1396/files#annotation_2946439517

**Review by ykuijs — CHANGES_REQUESTED** [review]
Have checked the code coverage locally and it indeed covers the specified lines. I think the code coverage merge has an issue here. I will check separately. We can ignore this issue in this PR.

Just a few minor comments

> Reviewed 3 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-:-MyptXzED1Tv1BvKCne8:b-dn19kf)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @ChristophHannappel and @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1, line 368 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-MypsmDP0pci8GSL368I:-MypsmDP0pci8GSL368J:b-ky98w9) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/360fab535d3ca0ed9766888ef2336a16caffcf55/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1#L368)):*
> ```PowerShell
>                 return $false
>             }
>             if ($searchADDomain.ContainsKey('CustomFilter') -and $searchADDomain.CustomFilter -ne $specifiedDomain.CustomFilter)
> ```

You can add these two new parameters to the Test-SPDscParameterState function a few line lower.

Because that function does not support checking credentials, the above check was specifically created.
___
*[SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1, line 396 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-Mypt9sV9yNF2AMTtEKJ:-Mypt9sV9yNF2AMTtEKK:b-skscn9) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/360fab535d3ca0ed9766888ef2336a16caffcf55/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1#L396)):*
> ```PowerShell
>             "ActiveDirectorySearchTimeout", `
>             "OnlySearchWithinSiteCollection",
>         "PeopleEditorOnlyResolveWithinSiteCollection")
> ```

Please add the two new parameters here.
___
*[tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettings.Tests.ps1, line 376 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-MxiNnMKOASbVbyuw5dd-r1-376:-MyptQ4BC1WGrmbiwc92:b-uikk5v) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/7330ff22f70bef0f56d3a46ea61b3927b56f7ee9/tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettings.Tests.ps1#L376)):*
<details><summary><i>Previously, ChristophHannappel wrote…</i></summary><blockquote>

On a subjective matter is this "Backtick-Pipe-Snake" the preferred way or something more readable like:
```powershell
$searchDom1 = New-Object -TypeName "Object"
Add-Member -InputObject $searchDom1 -MemberType 'NoteProperty' -Name LoginName -Value $mockAccount.UserName
Add-Member -InputObject $searchDom1 -MemberType 'NoteProperty' -Name CustomFilter -Value "(company=Contoso)"
Add-Member -InputObject $searchDom1 -MemberType 'NoteProperty' -Name ShortDomainName -Value "CONTOSO"
``` 
</blockquote></details>

This does look more readable indeed.

**Comment by ykuijs** [comment]
@ChristophHannappel Do you have the possibility to update this PR, so we can merge it?

**Comment by ChristophHannappel** [comment]
> @ChristophHannappel Do you have the possibility to update this PR, so we can merge it?

@ykuijs I'll try to do it this afternoon and give you a heads up after it :)

**Comment by ChristophHannappel** [comment]
> Have checked the code coverage locally and it indeed covers the specified lines. I think the code coverage merge has an issue here. I will check separately. We can ignore this issue in this PR.
> 
> Just a few minor comments
> 
> > Reviewed 3 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-:-MyptXzED1Tv1BvKCne8:b-dn19kf)_ status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @ChristophHannappel and @ykuijs)
> 
> _[SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1, line 368 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-MypsmDP0pci8GSL368I:-MypsmDP0pci8GSL368J:b-ky98w9) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/360fab535d3ca0ed9766888ef2336a16caffcf55/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1#L368)):_
> 
> > ```powershell
> >                 return $false
> >             }
> >             if ($searchADDomain.ContainsKey('CustomFilter') -and $searchADDomain.CustomFilter -ne $specifiedDomain.CustomFilter)
> > ```
> 
> You can add these two new parameters to the Test-SPDscParameterState function a few line lower.
> 
> Because that function does not support checking credentials, the above check was specifically created.
> 
> _[SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1, line 396 at r4](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-Mypt9sV9yNF2AMTtEKJ:-Mypt9sV9yNF2AMTtEKK:b-skscn9) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/360fab535d3ca0ed9766888ef2336a16caffcf55/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1#L396)):_
> 
> > ```powershell
> >             "ActiveDirectorySearchTimeout", `
> >             "OnlySearchWithinSiteCollection",
> >         "PeopleEditorOnlyResolveWithinSiteCollection")
> > ```
> 
> Please add the two new parameters here.
> 
> _[tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettings.Tests.ps1, line 376 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-MxiNnMKOASbVbyuw5dd-r1-376:-MyptQ4BC1WGrmbiwc92:b-uikk5v) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/7330ff22f70bef0f56d3a46ea61b3927b56f7ee9/tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettings.Tests.ps1#L376)):_
> 
> Previously, ChristophHannappel wrote…
> This does look more readable indeed.

I've moved the properties but now the Pester test fails. Since the properties are for the SearchActiveDirectoryDomains and not the people picker level, do i need to change something at the Test-DSCParameterState Command?

**Review by ykuijs — COMMENTED** [review]
You are absolutely right, I overlooked that part. The parameter should indeed be moved back to the original place, my bad! :smile: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-:-MzTiCMQCZs0BfpAmYAx:bq40fis)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ChristophHannappel and @ykuijs)

**Comment by ykuijs** [comment]
Also, make sure you update your branch with the main repo. I merged another PR earlier this week.

**Comment by ChristophHannappel** [comment]
> Also, make sure you update your branch with the main repo. I merged another PR earlier this week.

Thanks for the heads up! I did a rebase and currently a local build is running. After that i'll push the changes.

While working with the `Test-SPDscParameterState` I saw that the `ValuesToCheck` Array contained some backticks, but not not on all items.
https://github.com/dsccommunity/SharePointDsc/blob/139e5f740be3aac22fff6390fc5c79d1a5613090/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1#L324

```PowerShell
    $result = Test-SPDscParameterState -CurrentValues $CurrentValues `
        -Source $($MyInvocation.MyCommand.Source) `
        -DesiredValues $PSBoundParameters `
        -ValuesToCheck @("ActiveDirectoryCustomFilter", `
            "ActiveDirectoryCustomQuery", `
            "ActiveDirectorySearchTimeout", `
            "OnlySearchWithinSiteCollection",
        "PeopleEditorOnlyResolveWithinSiteCollection")
```

To me the reason for backticks seems to be that the Code Formatting looks a bit nicer.
Currently I've removed the Backticks from the array. I didn't find any guideline at the [DSC Resource Style Guidelines & Best Practices|https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#dsc-resource-style-guidelines--best-practices] to resolve this. Do you have a preference?

**Comment by ykuijs** [comment]
Great, have you seen this blog post about running individual unit tests: https://techcommunity.microsoft.com/t5/sharepointdsc-blog/announcement-making-running-unit-tests-easier-for-contributing/ba-p/3149068

Correct, when creating arrays the backticks are not required. I prefer without the backticks, which makes readability better (less unnecessary characters). So you removing them is perfect.

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 16 of 16 files at r6, 1 of 1 files at r7, all commit messages.
> Dismissed @ChristophHannappel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396#-:-MzZ2XM1EvQzs0q53KIP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChristophHannappel)

**Pull request merged**
