### PR TITLE
Update resource SPTrustedIdentityTokenIssuer to support OIDC

### PR DESCRIPTION
**Pull request by Yvand**
#### Pull Request (PR) description

Update resource SPTrustedIdentityTokenIssuer to support OIDC trust parameters, introduced with SharePoint Subscription

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369)

### CODE REVIEW

**Review by ykuijs — CHANGES_REQUESTED** [review]
Few comments

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-:-Ms_r85c8ws28Res7pi7:bec8so1)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @ykuijs and @Yvand)

___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 80 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qg-v0ao8Dvr6WIM-:-Ms_qg-v0ao8Dvr6WIM0:b-2ckzxf) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L80)):*
> ```PowerShell
> 
>     Write-Verbose -Message "Getting SPTrustedIdentityTokenIssuer '$Name' settings"
> ```

Shouldn't we check if OIDC parameters are used and SPSE isn't used? And if so, throw an exception? Like we do here:
https://github.com/dsccommunity/SharePointDsc/blob/6de479242665ffc440fccac93f3501d36504b36f/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1#L27-L39
___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 236 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qLxtD4c_LgnYhsGG:-Ms_qLxtD4c_LgnYhsGH:b-2ckzxf) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L236)):*
> ```PowerShell
>     Write-Verbose -Message "Setting SPTrustedIdentityTokenIssuer '$Name' settings"
> 
>     $CurrentValues = Get-TargetResource @PSBoundParameters
> ```

Shouldn't we check if OIDC parameters are used and SPSE isn't used? And if so, throw an exception? Like we do here:
https://github.com/dsccommunity/SharePointDsc/blob/6de479242665ffc440fccac93f3501d36504b36f/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1#L27-L39
___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 304 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_pawT-kidvwnhLFQ5:-Ms_pawT-kidvwnhLFQ6:bn2z9vo) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L304)):*
> ```PowerShell
>             # OIDC trust: If parameter DefaultClientIdentifier is set, 
>             # then parameters AuthorizationEndPointUri and SignOutUrl are required
>             if ($true -eq $PSBoundParameters.ContainsKey("DefaultClientIdentifier") -and (
> ```

Looking at the code below, where the oidcsetup is true and the RegisteredIssuerName parameter is added:
Shouldn't the RegisteredIssuerName also be specified when using OIDC?
___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 605 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qina4q7Hyw8p0cEI:-Ms_qina4q7Hyw8p0cEJ:b-2ckzxf) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L605)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message "Testing SPTrustedIdentityTokenIssuer '$Name' settings"
> ```

Shouldn't we check if OIDC parameters are used and SPSE isn't used? And if so, throw an exception? Like we do here:
https://github.com/dsccommunity/SharePointDsc/blob/6de479242665ffc440fccac93f3501d36504b36f/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1#L27-L39
___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 669 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_q52Q2KnddjI7kC--:-Ms_q52Q2KnddjI7kC-0:b-g0aov8) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L669)):*
> ```PowerShell
>     # OIDC trust: If parameter DefaultClientIdentifier is set, 
>     # then parameters AuthorizationEndPointUri and SignOutUrl are required
>     if ($true -eq $PSBoundParameters.ContainsKey("DefaultClientIdentifier") -and (
> ```

Same as before: Shouldn't RegisteredIssuerName also be specified when using OIDC?
___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md, line 31 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_r3Sb1UU4GX_Y0J7d:-Ms_r3Sb1UU4GX_Y0J7e:b-lxn7jc) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md#L31)):*
> ```Markdown
> 
> For an OIDC trust, the specific mandatory parameters are 
> AuthorizationEndPointUri, DefaultClientIdentifier and SignOutUrl.
> ```

As before: What about RegisteredIssuerName?

**Comment by ykuijs** [comment]
Could you also update the Pester tests to test for these new scenarios?

**Review by ykuijs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @ykuijs and @Yvand)

___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 80 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qg-v0ao8Dvr6WIM-:-MsdZGiT9Wg2_BW2s8_k:b-96cw4f) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L80)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary><blockquote>

Would it not be a useless extra effort?
I meat that if someone does that, New-SPTrustedIdentityTokenIssuer will just throw an exception saying that the parameters do not exist.
</blockquote></details>

Understand your point. However, the New-SPTrustedIdentityTokenIssuer cmdlet is called further down the code and it will throw an error similar to "Parameter not valid or something", not indicating this is related to the version of SharePoint.

If we add this check at the beginning of each *-TargetResource method, we can throw a clear and meaningful message telling the admin that the specified parameter is not valid for the used version of SharePoint. This also makes sure the error is thrown early in the process, preventing PowerShell from processing lines of code that are never going to result in anything.

**Review by ykuijs — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ykuijs and @Yvand)

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 80 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qg-v0ao8Dvr6WIM-:-Msf7FtVExpgDsbl6BdZ:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L80)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Understand your point. However, the New-SPTrustedIdentityTokenIssuer cmdlet is called further down the code and it will throw an error similar to "Parameter not valid or something", not indicating this is related to the version of SharePoint.

If we add this check at the beginning of each *-TargetResource method, we can throw a clear and meaningful message telling the admin that the specified parameter is not valid for the used version of SharePoint. This also makes sure the error is thrown early in the process, preventing PowerShell from processing lines of code that are never going to result in anything.
</blockquote></details>

Done.

**Comment by Yvand** [comment]
@ykuijs I fixed all the errors except this one, which occurs 2 times:

```
Context A OIDC SPTrustedLoginProvider is desired, but not all required OIDC properties are set
[-] should fail validation of parameters 46ms
ParameterBindingException: Parameter 'Throw' cannot be specified in parameter set 'Legacy'.
at <ScriptBlock>, D:\a\1\s\Tests\Unit\SharePointDsc\SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1: line 477
```

The code that fails is the following (in MSFT_SPTrustedIdentityTokenIssuer.psm1):

```powershell
It "should fail validation of parameters" {
	{ Set-TargetResource @testParams } | Should -Throw "Parameter DefaultClientIdentifier was set but AuthorizationEndPointUri, RegisteredIssuerName or SignOutUrl are not set." + `
		"Parameters AuthorizationEndPointUri, RegisteredIssuerName, DefaultClientIdentifier and SignOutUrl are required when DefaultClientIdentifier is set"
}
```

I copied this from existing tests, how should it be done?

**Comment by Yvand** [comment]
@ykuijs is the pipeline stuck?

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 236 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qLxtD4c_LgnYhsGG:-MtDoOTZAZx7uELfMs5K:bb6un1j) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L236)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary><blockquote>

Would it not be a useless extra effort?
I meat that if someone does that, New-SPTrustedIdentityTokenIssuer will just throw an exception saying that the parameters do not exist.
</blockquote></details>

Done
___
*[SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1, line 605 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-Ms_qina4q7Hyw8p0cEI:-MtDoR4u95W9QvMQbYso:bb6un1j) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/2ebe9f2680ee1aac38db1a2f611e79d898ea37a8/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1#L605)):*
<details><summary><i>Previously, Yvand (Yvan Duhamel) wrote…</i></summary><blockquote>

Would it not be a useless extra effort?
I meat that if someone does that, New-SPTrustedIdentityTokenIssuer will just throw an exception saying that the parameters do not exist.
</blockquote></details>

Done

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369#-:-MtdfE_QEp6tgmg5AYC9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yvand)

**Pull request merged**
