### PR TITLE
SPWebAppSuiteBar: Unblocked configuration for SP2019

### LINKED ISSUE #1139: SPWebAppSuiteBar: Resource not working with SP2019, add notifications to the resource
ISSUE TITLE:
    SPWebAppSuiteBar is not working with 2019.

ISSUE DESCRIPTION (this template):
    When I ran this module for SP 201 it is working as expectd but when run on 2019 it is not able to make changes as required.
I look in few forums and it has been confirmed this is not supported in 2019 version as "SharePoint" text is hard coded and even CSS is only able to work on classic pages and not modern pages.

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description

Unblocked configuration for SP2019. This resource works fine on SharePoint 2019 as long as it's not expected that it affects modern pages.
Verbose messages has been added to clarify this.

#### This Pull Request (PR) fixes the following issues

- Fixes #1139
- Reverts SP2019 blocking introduced in #1210

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1240)

### CODE REVIEW

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1240#-:-MI0dYHS0doLWwGB_VvE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ykuijs** [comment]
Merging as soon as the tests complete successfully

**Comment by ykuijs** [comment]
@jensotto There are four [tests failing](https://dev.azure.com/dsccommunity/d5d03a7a-2a04-4e7a-ba10-7318f3b25280/_apis/build/builds/2969/logs/37) under SP2019:
```
2020-09-24T22:14:38.9776847Z Executing script D:\a\1\s\Tests\Unit\SharePointDsc\SharePointDsc.SPWebAppSuiteBar.Tests.ps1
2020-09-24T22:14:39.1985148Z 
2020-09-24T22:14:39.2010033Z   Describing [SP Build: 16.0.10337.12109] DSC Resource 'SPWebAppSuiteBar'
2020-09-24T22:14:40.3910178Z 
2020-09-24T22:14:40.3938016Z     Context Web application does not exist
2020-09-24T22:14:41.8068641Z       [+] Get target resource returns null value 913ms
2020-09-24T22:14:42.1505452Z 
2020-09-24T22:14:42.1537140Z     Context Only all SP2016 parameters passed for a SP2016 environment
2020-09-24T22:14:43.8313369Z       [-] successfully returns the suite bar properties 841ms
2020-09-24T22:14:43.9479401Z         Expected 'http://sites.sharepoint.com', but got $null.
2020-09-24T22:14:43.9517872Z         222:                         $results.SuiteNavBrandingLogoNavigationUrl | Should be "http://sites.sharepoint.com"
2020-09-24T22:14:43.9580432Z         at <ScriptBlock>, D:\a\1\s\Tests\Unit\SharePointDsc\SharePointDsc.SPWebAppSuiteBar.Tests.ps1: line 222
2020-09-24T22:14:45.6010357Z       [+] Should properly configure the suite bar for the Web Application 1.47s
2020-09-24T22:14:47.2115280Z       [-] Should return true from the test method 1.39s
2020-09-24T22:14:47.2816543Z         Expected $true, but got $false.
2020-09-24T22:14:47.2817647Z         234:                         Test-TargetResource @testParams | Should Be $true
2020-09-24T22:14:47.2898344Z         at <ScriptBlock>, D:\a\1\s\Tests\Unit\SharePointDsc\SharePointDsc.SPWebAppSuiteBar.Tests.ps1: line 234
2020-09-24T22:14:47.6181569Z 
2020-09-24T22:14:47.6205989Z     Context Only some SP2016 parameters passed for a SP2016 environment
2020-09-24T22:14:48.9669317Z       [-] successfully returns the suite bar properties 709ms
2020-09-24T22:14:49.0216171Z         Expected 'http://sites.sharepoint.com', but got $null.
2020-09-24T22:14:49.0322040Z         264:                         $results.SuiteNavBrandingLogoNavigationUrl | Should be "http://sites.sharepoint.com"
2020-09-24T22:14:49.0363548Z         at <ScriptBlock>, D:\a\1\s\Tests\Unit\SharePointDsc\SharePointDsc.SPWebAppSuiteBar.Tests.ps1: line 264
2020-09-24T22:14:50.5756984Z       [+] Should properly configure the suite bar for the Web Application 1.37s
2020-09-24T22:14:51.8717929Z       [-] Should return true from the test method 1.09s
2020-09-24T22:14:51.9106387Z         Expected $true, but got $false.
2020-09-24T22:14:51.9166057Z         275:                         Test-TargetResource @testParams | Should Be $true
2020-09-24T22:14:51.9218606Z         at <ScriptBlock>, D:\a\1\s\Tests\Unit\SharePointDsc\SharePointDsc.SPWebAppSuiteBar.Tests.ps1: line 275
```

**Comment by jensotto** [comment]
Sorry, didn't run the tests for SP2019 locally it seems. I did it now and have removed a check for SP2019 in the Get-TargetResource method.

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1240#-:-MI4Sxfb5B-6xtKAJ6nf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
