### PR TITLE
SPContentDatabase / SPUserProfileProperty

### LINKED ISSUE #1157: MSFT_SPContentDatabase: Checking existing database always throw exception
#### Details of the scenario you tried and the problem that is occurring

Repo step:
1. Create new content database passing only name and webapplication
2. Ensure database is created
3. Run same script again
4. Get exception:
`Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance.`

#### Verbose logs showing the problem

```
Set-ContentDatabase -Name $ContentDatabaseName -WebAppUrl $WebApplication -Ensure Present -Debug
VERBOSE: Executing as the local run as user user
VERBOSE: Leaving BeginProcessing Method of Get-SPDatabase.
VERBOSE: Leaving ProcessRecord Method of Get-SPDatabase.
VERBOSE: Leaving EndProcessing Method of Get-SPDatabase.
VERBOSE: Leaving BeginProcessing Method of Get-SPWebApplication.
VERBOSE: Leaving ProcessRecord Method of Get-SPWebApplication.
VERBOSE: Leaving EndProcessing Method of Get-SPWebApplication.
Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance.
At line:32 char:21
+ ...             throw ("Specified database server does not match the actu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Specified datab...t SQL instance.:String) [], RuntimeException
    + FullyQualifiedErrorId : Specified database server does not match the actual database server. This resource cannot move the database to a different SQL instance.
```
Here Set-ContentDatabase is Set-TargetResource. I just call it explicitly from resource file.

#### Suggested solution to the issue
```
if ($cdb.Server -ne $params.DatabaseServer)
                {
                    throw ("Specified database server does not match the actual database " + `
                            "server. This resource cannot move the database to a different " + `
                            "SQL instance.")
                }
```
This validation is always throw exception if I do not pass DatabaseServer param to resource (and I really don't wanna pass it).

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
```

### LINKED ISSUE #1164: MSFT_SPUserProfileProperty - Added property, fixed bug
Hi there,

found a bug in MSFT_SPUserProfileProperty.psm1 (module version 3.7.0.0), line 891:

`return Test-SPDscParameterState -CurrentValues $CurrentValues `
            -DesiredValues $PSBoundParameters `
            -ValuesToCheck @("Name",
            "DisplayName",
            "Type",
            "Description",
            "PolicySetting",
            "PrivacySetting",
            "PropertyMappings",
            "Length",
            "DisplayOrder",
            "IsEventLog",
            "IsVisibleOnEditor",
            "IsVisibleOnViewer",
            "IsUserEditable",
            "IsAlias",
            "IsSearchabe",
            "UserOverridePrivacy",
            "TermGroup",
            "TermStore",
            "TermSet",
            "Ensure")`

String 'IsSearchabe' should be 'IsSearchable'

Furthermore, I suggest to add ability to set the property 'isReplicable', proposed solution is attached.

Thanks...
[MSFT_SPUserProfileProperty.zip](https://github.com/dsccommunity/SharePointDsc/files/4185149/MSFT_SPUserProfileProperty.zip)

### PR DESCRIPTION
**Pull request by ruandersMSFT**
#### Pull Request (PR) description

SPUserProfileProperty Fix IsSearchable / Add IsReplicable

#### This Pull Request (PR) fixes the following issues

- Fixes #1157 SPContentDatabase
- Fixes #1164 SPUserProfileProperty

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [X] Resource documentation added/updated in README.md.
- [X] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1174)

### CODE REVIEW

**Comment by ykuijs** [comment]
A change in one of the CD/CI modules is causing the unit tests to fail. Will submit a PR to have this issue fixed, after which you can update your branch from master.

**Comment by ykuijs** [comment]
I was wrong, this wasn't caused by an updated module. You targeted this PR against dev, but we are not using the dev branch anymore. Can you please update from master and retarget the PR to master?

**Comment by ruandersMSFT** [comment]
@ykuijs Ok, thanks for the awareness.  I did target Dev thinking that was still the approach.  I will target this against master this evening (and should have a few more items in there as well).

**Comment by ykuijs** [comment]
No problem, removing the dev branch is still on my ToDo list :-)

**Comment by ykuijs** [comment]
Had to update the PR with recently merged changes. Will merge this PR as soon as the tests complete.

**Pull request merged**
