### PR TITLE
Bugfix PR

### LINKED ISSUE #1199: SPWebAppAuthentication: Add management of "Require Use Remote Interfaces", "Custom Sign in page" and AllowAnonymousAuth
#### ISSUE TITLE:
    'SPWebAppAuthentication : NTLM, anonymous and FBA on default zone'
    

####ISSUE DESCRIPTION
How would i go by and set all these settings on the default Zone?

-Enable anonymous access
-Require Use Remote Interfaces permissions
-Enable Windows Authentication and Integraded Windows authentication NTLM
-Enable Forms Based Authentication (FBA)
-Custom sign in page


In the example on the https://github.com/dsccommunity/SharePointDsc/wiki/SPWebAppAuthentication site, they use another zone for hte FBA, but i need to use only default. This is configurable via GUI.

#### Details of the scenario you tried and the problem that is occurring
I am not able to set both NTLM and FBA on the default zone.
#### Verbose logs showing the problem

#### Suggested solution to the issue

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# insert configuration here
```

#### The operating system the target node is running

<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19678.amd64fre.winblue_ltsb_escrow.200330-1737
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2013

#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                                                                                                                                                                                                                      
----                           -----                                                                                                                                                                                                                                                                                                                      
PSVersion                      5.1.14409.1018                                                                                                                                                                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                                                                                                    
BuildVersion                   10.0.14409.1018                                                                                                                                                                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                                                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                                                                                                        
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used
SharePointDsc -ModuleVersion 3.8.0

### LINKED ISSUE #1248: SPUserProfileProperty: multiple AD property mapping
#### Details of the scenario you tried and the problem that is occurring

Trying to map `FirstName` profile property to two AD attributes. As the result, I only get one attribute mapped:
image

#### Verbose logs showing the problem

Start:
```
VERBOSE: [SWAZSERVER03]: LCM:  [ Start  Resource ]  [[SPUserProfileProperty]FirstName]
VERBOSE: [SWAZSERVER03]: LCM:  [ Start  Test     ]  [[SPUserProfileProperty]FirstName]
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Testing for user profile
property FirstName
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Getting user profile property
FirstName
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Executing as the local run as
user CONTOS00\_spadm
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Current Values: Description=;
DisplayName=First name; DisplayOrder=5; Ensure=Present; IsAlias=False; IsEventLog=False; IsReplicable=True;
IsSearchable=True; IsUserEditable=False; IsVisibleOnEditor=False; IsVisibleOnViewer=False; Length=250; Name=FirstName;
PolicySetting=OptIn; PrivacySetting=Public; PropertyMappings=({ConnectionName=c0nt0s00-local; Direction=Import;
PropertyName=msDS-PhoneticFirstName},{ConnectionName=c0nt0s00-local; Direction=Import;
PropertyName=msDS-PhoneticFirstName}); TermGroup=; TermSet=; TermStore=; Type=string (Single Value);
UserOverridePrivacy=False; UserProfileService=User Profile Service Application
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Target Values: Ensure=Present;
Name=FirstName; PropertyMappings=({ConnectionName=c0nt0s00-local; PropertyName=msDS-PhoneticFirstName;
Direction=Import},{ConnectionName=c0nt0s00-local; PropertyName=givenName; Direction=Import}); UserProfileService=User
Profile Service Application; Verbose=True
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Test-TargetResource returned
False
VERBOSE: [SWAZSERVER03]: LCM:  [ End    Test     ]  [[SPUserProfileProperty]FirstName]  in 0.3600 seconds.
VERBOSE: [SWAZSERVER03]: LCM:  [ Start  Set      ]  [[SPUserProfileProperty]FirstName]
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Setting user profile property
FirstName
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Executing as the local run as
user CONTOS00\_spadm
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]: LCM:  [ End    Set      ]  [[SPUserProfileProperty]FirstName]  in 0.5150 seconds.
VERBOSE: [SWAZSERVER03]: LCM:  [ End    Resource ]  [[SPUserProfileProperty]FirstName]
```

Test:

```
VERBOSE: [SWAZSERVER03]: LCM:  [ Start  Resource ]  [[SPUserProfileProperty]FirstName]
VERBOSE: [SWAZSERVER03]: LCM:  [ Start  Test     ]  [[SPUserProfileProperty]FirstName]
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Testing for user profile
property FirstName
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Getting user profile property
FirstName
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Executing as the local run as
user CONTOS00\_spadm
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPServiceApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPWebApplication.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving BeginProcessing Method
of Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving ProcessRecord Method of
Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Leaving EndProcessing Method of
Get-SPServiceContext.
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Current Values: Description=;
DisplayName=First name; DisplayOrder=5; Ensure=Present; IsAlias=False; IsEventLog=False; IsReplicable=True;
IsSearchable=True; IsUserEditable=False; IsVisibleOnEditor=False; IsVisibleOnViewer=False; Length=250; Name=FirstName;
PolicySetting=OptIn; PrivacySetting=Public; PropertyMappings=({ConnectionName=c0nt0s00-local; Direction=Import;
PropertyName=givenName},{ConnectionName=c0nt0s00-local; Direction=Import; PropertyName=givenName}); TermGroup=;
TermSet=; TermStore=; Type=string (Single Value); UserOverridePrivacy=False; UserProfileService=User Profile Service
Application
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Target Values: Ensure=Present;
Name=FirstName; PropertyMappings=({ConnectionName=c0nt0s00-local; PropertyName=msDS-PhoneticFirstName;
Direction=Import},{ConnectionName=c0nt0s00-local; PropertyName=givenName; Direction=Import}); UserProfileService=User
Profile Service Application; Verbose=True
VERBOSE: [SWAZSERVER03]:                            [[SPUserProfileProperty]FirstName] Test-TargetResource returned
False
VERBOSE: [SWAZSERVER03]: LCM:  [ End    Test     ]  [[SPUserProfileProperty]FirstName] False in 0.4370 seconds.
VERBOSE: [SWAZSERVER03]: LCM:  [ End    Resource ]  [[SPUserProfileProperty]FirstName]
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
        SPUserProfileProperty FirstName
        {
            Name                    = "FirstName"
            UserProfileService      = "User Profile Service Application"
            PropertyMappings        = @(
                MSFT_SPUserProfilePropertyMapping {
                    ConnectionName  = (Get-WmiObject win32_computersystem).Domain.Replace( ".", "-" )
                    PropertyName    = "msDS-PhoneticFirstName"
                    Direction       = "Import"
                }
                MSFT_SPUserProfilePropertyMapping {
                    ConnectionName  = (Get-WmiObject win32_computersystem).Domain.Replace( ".", "-" )
                    PropertyName    = "givenName"
                    Direction       = "Import"
                }
            )
            PsDscRunAsCredential    = $SPInstallAccountCredential
            DependsOn               = "[SPUserProfileSyncConnection]DefaultConnection"
        }
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)

SharePoint 2019

#### Version and build of PowerShell the target node is running

```
Name                           Value
----                           -----
PSRemotingProtocolVersion      2.3
BuildVersion                   10.0.17763.1490
PSVersion                      5.1.17763.1490
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Desktop
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used

4.2.0

### LINKED ISSUE #1311: [SPSearchServiceApp] Farm account to have db_owner permissions on all Search DBs
#### Details of the scenario you tried and the problem that is occurring
In issue #1289 @rurikon mentioned an issue that occurs when provisioning the Search Service App via PowerShell:

One thing I did notice while doing this is that setting search administrators with SPServiceAppSecurity doesn't work properly either. I have and administrator AD group and while it looks like it's added in the UI, on database level the group doesn't get access to the search databases. When I remove it and add again manually, the database rights are correct. That might explain why I kept having issues where the service pool account's rights would be dropped from one database as described in this blog: https://www.techmikael.com/2014/10/caution-if-you-have-used.html (this happened even though I started creating the service itself with the farm account so it gets the right db owner). This doesn't affect the property issue, but is worth noting if someone else is having the same kind of problems.

#### Suggested solution to the issue
Add logic to make sure the farm account has db_owner permissions on all Search DBs

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used
dev

### LINKED ISSUE #1318: [SPFarm] Creating Lock database does not work because the user doesn't have permissions to create the lock table in the TempDB
#### Details of the scenario you tried and the problem that is occurring
When the user doesn't have sysadmin permissions or is has permissions to create tables in the TempDB, the SPFarm resource fails with error “CREATE TABLE permission denied in database 'tempdb'”

@Fiander has created a PR which changes the lock table to a global temporary table #1314. We need to incorporate this into SPDsc.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used
Dev

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

Bugfix PR that fixes several issues

#### This Pull Request (PR) fixes the following issues

- Fixes #1199 
- Fixes #1248 
- Fixes #1311 
- Fixes #1318 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Up for a review.

I will fix the unit tests in the meantime 😉

**Review by NikCharlebois — COMMENTED** [review]
Fewof things to check

> Reviewed 18 of 19 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-:-MbkSjTk2fk-ju-GYilK:b-qkmwpk)* status: all files reviewed, 3 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 159 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-MbkHud_5MTb0icVirbK:-MbkHud_5MTb0icVirbL:b4uxz4c) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/f6dbc53a513c781c59a756bd4620e69d6caae8c4/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L159)):*
> ```PowerShell
>             Write-Verbose -Message "Checking Admin Database"
>             $adminDB = $serviceApp.SearchAdminDatabase.Name
>             if ($correctFarmAccountPermissions -eq $true)
> ```

How can it ever be anything other than true at this stage?
___
*[SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 212 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-MbkRIMi1NFvtrP4r6VP:-MbkRIMj2dZAgUZkawCs:b-gbqe8h) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/f6dbc53a513c781c59a756bd4620e69d6caae8c4/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L212)):*
> ```PowerShell
>                 CloudIndex                  = $cloudIndex
>                 AlertsEnabled               = $serviceApp.AlertsEnabled
>                 FixFarmAccountPermissions   = $correctFarmAccountPermissions
> ```

Just want to make sure I understand the logic here. If the variable FixFarmAccountPermissions is set to True, that means the permissions are already correct? If so, why are we saying later that if the variable is set to true then we need to fix the permissions if they are already correct? 
___
*[SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 510 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-MbkReLF1ThmWGwAdx8V:-MbkReLF1ThmWGwAdx8W:b-agwlv4) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/f6dbc53a513c781c59a756bd4620e69d6caae8c4/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L510)):*
> ```PowerShell
>     }
> 
>     # Only check and correct when Ensure=Present, FixFarmAccountPermissions=True and the permissions are incorrect
> ```

Based on my understanding and comment above, if FixFarmAccountPermission is True that means the permissions are already correct, so why would we need to fix them?

**Review by ykuijs — COMMENTED** [review]
Great feedback! I have reversed the use of the parameter, so it makes more sense.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-:-Mblj5yY21hy8B6ozMRz:b-gfpii9)* status: 18 of 20 files reviewed, 3 unresolved discussions (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 159 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-MbkHud_5MTb0icVirbK:-MbliO-v4hnR_22_NFLH:b-g0o994) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/f6dbc53a513c781c59a756bd4620e69d6caae8c4/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L159)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

How can it ever be anything other than true at this stage?
</blockquote></details>

Good point, removed this if statement
___
*[SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 212 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-MbkRIMi1NFvtrP4r6VP:-MbliR_N8f0IVbC3KqO-:b5mwmuo) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/f6dbc53a513c781c59a756bd4620e69d6caae8c4/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L212)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Just want to make sure I understand the logic here. If the variable FixFarmAccountPermissions is set to True, that means the permissions are already correct? If so, why are we saying later that if the variable is set to true then we need to fix the permissions if they are already correct? 
</blockquote></details>

I understand your confusion and this doesn't make sense. It will also make the Verbose output inconsistent. So I reverse the logic. If FixFarmAccountPermissions=$true, the permissions need to get fixed. When it is $false, they are fine. Exactly like the same parameter of the methods.
___
*[SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1, line 510 at r2](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-MbkReLF1ThmWGwAdx8V:-MblitWoAC7ZbdJdYpsC:bi8fheh) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/f6dbc53a513c781c59a756bd4620e69d6caae8c4/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1#L510)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Based on my understanding and comment above, if FixFarmAccountPermission is True that means the permissions are already correct, so why would we need to fix them?
</blockquote></details>

This check was testing if the Desired parameter was True and the Current value was False. Because of the above update, this is now both checking for True, which makes more sense.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1319#-:-MblscPO0cNgMEZM37A9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Pull request merged**
