### PR TITLE
Added native ReverseDsc support

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This PR adds native ReverseDsc support to SharePointDsc. This means that the ReverseDsc module has become a required module, but you no longer need to use the SharePoint Orchestration script.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279)

### CODE REVIEW

**Review by NikCharlebois — COMMENTED** [review]
Couple of very minor pieces of feedback

> Reviewed 158 of 158 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-:-MRWn-Mz3NxKBu7DZXcb:b-he8azq)* status: all files reviewed, 3 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 1413 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-MRWkC9wCi5Sk--ahpch:-MRWkC9wCi5Sk--ahpci:b-cecg4t) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/b7071ac60a72d6b17869634d64a77b4841f4fea7/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L1413)):*
> ```PowerShell
> 
>     $spCentralAdmin = Get-SPWebApplication -IncludeCentralAdministration | Where-Object { $_.DisplayName -like '*Central Administration*' }
>     <# WA - Bug in 1.6.0.0 Get-TargetResource does not return the current Authentication Method; #>
> ```

May need to revisit this part :) But maybe at a later time
___
*[SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 837 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-MRWkvve2b9xrU0zO_HN:-MRWkvve2b9xrU0zO_HO:bmno1af) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/b7071ac60a72d6b17869634d64a77b4841f4fea7/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L837)):*
> ```PowerShell
>             if ($null -ne $ups)
>             {
>                 Write-Host "`r`nW103"  -BackgroundColor Yellow -ForegroundColor Black -NoNewline
> ```

These codes were related to something we tried implementing at some point where we would build a glossary of error codes with better descriptions. We never got to it unfortunately. Maybe we don't want to print those anymore and just stick with the error on the line below
___
*[SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 1665 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-MRWmFkS6gheGK8Ktewd:-MRWmFkT-Sb0gZ_9katE:b-48gn3v) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/b7071ac60a72d6b17869634d64a77b4841f4fea7/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L1665)):*
> ```PowerShell
>     else
>     {
>         Write-Host -Object "`r`nE102"  -BackgroundColor Red -ForegroundColor Black -NoNewline
> ```

Same thing about the error codes

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279)* status: all files reviewed, 3 unresolved discussions (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 1413 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-MRWkC9wCi5Sk--ahpch:-MRaple14HJuJpOft6LZ:b-l9gk0e) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/b7071ac60a72d6b17869634d64a77b4841f4fea7/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L1413)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

May need to revisit this part :) But maybe at a later time
</blockquote></details>

Good point. Updated this one, since that was an easy one. Will create an issue to revisit others later.
___
*[SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1, line 837 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-MRWkvve2b9xrU0zO_HN:-MRapwP53u4XNWw258MV:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/b7071ac60a72d6b17869634d64a77b4841f4fea7/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1#L837)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

These codes were related to something we tried implementing at some point where we would build a glossary of error codes with better descriptions. We never got to it unfortunately. Maybe we don't want to print those anymore and just stick with the error on the line below
</blockquote></details>

Done.
___
*[SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1, line 1665 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-MRWmFkS6gheGK8Ktewd:-MRapxRk5O6qt-4WrG7Y:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/b7071ac60a72d6b17869634d64a77b4841f4fea7/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L1665)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Same thing about the error codes
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-:-MReQpr1B3mkqUhkvE2n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1279#-:-MS-ABbdAWKvBOKtH_sL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
