### PR TITLE
SPWebApplication: Use of SecureSocketsLayer Parameter

### LINKED ISSUE #1394: [SPWebApplication] Calls Set-SPWebApplication with non existing Parameter SecureSocketsLayer
### Problem description

The [Set Function](https://github.com/dsccommunity/SharePointDsc/blob/fe2111d3c911e2b5ddd7f14855f1a17c32ff0047/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L623) for SPWebApplication adds the `SecureSocketsLayer` Parameter to the `Set-SPWebApplication` function, if the WebApplication URL has an https scheme.

In SharePoint Server 2019 the Set-SPWebApplication Function does not have a parameter SecureSocketsLayer 
```PowerShell
Add-PSSnapin -Name Microsoft.SharePoint.PowerShell
Get-Command -Name Set-SPWebApplication -Syntax

Set-SPWebApplication [-Identity] <SPWebApplicationPipeBind> [-DefaultTimeZone <int>] [-DefaultQuotaTemplate <string>] [-ServiceApplicationProxyGroup <SPServiceApplicationProxyGroupPipeBi
nd>] [-Force] [-NotProvisionGlobally] [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf] [-Confirm] [<CommonParameters>]

Set-SPWebApplication [-Identity] <SPWebApplicationPipeBind> -Zone <SPUrlZone> [-AuthenticationProvider <SPAuthenticationProviderPipeBind[]>] [-AdditionalClaimProvider <SPClaimProviderPip
eBind[]>] [-SignInRedirectURL <string>] [-SignInRedirectProvider <SPTrustedIdentityTokenIssuerPipeBind>] [-AuthenticationMethod <string>] [-Force] [-NotProvisionGlobally] [-AssignmentCol
lection <SPAssignmentCollection>] [-WhatIf] [-Confirm] [<CommonParameters>]

Set-SPWebApplication [-Identity] <SPWebApplicationPipeBind> -SMTPServer <string> [-DisableSMTPEncryption] [-SMTPCredentials <pscredential>] [-SMTPServerPort <int>] [-OutgoingEmailAddress
 <string>] [-ReplyToEmailAddress <string>] [-Force] [-NotProvisionGlobally] [-AssignmentCollection <SPAssignmentCollection>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

### Verbose logs

```text
VERBOSE: [Servername]: LCM:  [ End    Set      ]  [[SPWebApplication]Portal::[SharePointWebApplications]SharePointWebApplications]  in 1.
8040 seconds.
PowerShell DSC resource MSFT_SPWebApplication  failed to execute Set-TargetResource functionality with error message: A parameter 
cannot be found that matches parameter name 'SecureSocketsLayer'. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

### DSC configuration

```powershell
SPWebApplication HostNameSiteCollectionWebApp
{
	Name                   = "SharePoint Sites"
	ApplicationPool        = "SharePoint Sites"
	ApplicationPoolAccount = "CONTOSO\svcSPWebApp"
	WebAppUrl              = "https://example.contoso.local"
	Port                   = 443
	AllowAnonymous         = $false
	PsDscRunAsCredential   = $SetupAccount
}

# Enable the Anonymous Authentication and run the DSC Configuration to recreate the bug.
```

### Suggested solution

Put the [Code Block](https://github.com/dsccommunity/SharePointDsc/blob/fe2111d3c911e2b5ddd7f14855f1a17c32ff0047/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L623) into the SharePoint Server Subscription Edition IF block
https://github.com/dsccommunity/SharePointDsc/blob/fe2111d3c911e2b5ddd7f14855f1a17c32ff0047/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1#L627

### SharePoint version and build

```text
SharePoint Server 2019 16.0.10382.20004
```

### Operating system the target node is running

```text
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

### PowerShell version and build the target node is running

```text
Name                           Value                                                                                                                                                     
----                           -----                                                                                                                                                     
PSVersion                      5.1.17763.2268                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                   
BuildVersion                   10.0.17763.2268                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                       
SerializationVersion           1.1.0.1
```

### SharePointDsc version

```text
Name          Version Path                                                                             
----          ------- ----                                                                             
SharePointDSC 5.1.0   C:\Program Files\WindowsPowerShell\Modules\SharePointDSC\5.1.0\SharePointDSC.psd1
```

### PR DESCRIPTION
**Pull request by ChristophHannappel**
#### Pull Request (PR) description

Fixed an issue where the Set method tried to use the Parameter SecureSocketsLayer with Set-SPWebApplication on SharePoint Server older than Subscription Edition.

#### This Pull Request (PR) fixes the following issues

- Fixes #1394

#### Task list

- [X] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [X] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1395)

### CODE REVIEW

**Comment by ykuijs** [comment]
Hi @ChristophHannappel, The SecureSocketsLayer parameter also existed pre-Subscription Edition, but then didn't configure IIS like Subscription Edition is now able to. But it did configure the HTTPS host header names, etc. So I think this PR will break those scenarios.

**Comment by ykuijs** [comment]
Correction. Added more details and explanation to issue #1394. Will review this PR

**Review by ykuijs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1395#-:-MxeL8uMAcBnH7pmulye:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ykuijs)

___
*[CHANGELOG.md, line 9 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1395#-MxeKQCW631ncWg2oRod:-MxeL33k085rbqF6jjvc:b-etlclm) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/878fe844161b758b29016f22ba1066bbb20ff8ae/CHANGELOG.md#L9)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

I think the HQRM tests will fail because there is not empty line between the Fixed header and the first item. If that is not the case, I will fix this later.
</blockquote></details>

Looks like it is not failing :smile:

**Review by ykuijs — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1395)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ChristophHannappel)

**Comment by ykuijs** [comment]
Why did you close this PR??

**Comment by ChristophHannappel** [comment]
yeah, in an attempt to clean up my fork repo - i deleted the wrong branches :( which than closed the pull request.  Unfortunately there was no warning from the github ui about an open pull request.  I'll recreate it tomorrow, sorry for the confusion.

**Pull request merged**
