### PR TITLE
[SPDocIcon] Added new resource

### LINKED ISSUE #1276: Support for adding custom file type icons
It would be great to have a resource to add custom file type icons to SharePointDSC.

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This PR adds a new resource called SPDocIcon, which is able to configure file types in the DocIcon XML file.

#### This Pull Request (PR) fixes the following issues

- Fixes #1276 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Can you review this PR?

**Review by NikCharlebois — COMMENTED** [review]
Few comments

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-:-MS7yH5I8UqfpTStbuP8:bec8so1)* status: all files reviewed, 4 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1, line 38 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7qv0T5HIKsqbJkevK:-MS7qv0T5HIKsqbJkevL:b-vpsb2f) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1#L38)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message "Getting status of $FileType in 'docicon.xml'"
> ```

Should the file type be passed with the '.' in front. I think not, but some users will pass it. Should we handle this scenario or print an error if they include the '.'?
___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1, line 128 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7wuqkDPzGm6YV7ZHI:-MS7wuql2GPo4mdYg1Zk:bg006rj) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1#L128)):*
> ```PowerShell
>     Write-Verbose -Message "Setting status of $FileType in 'docicon.xml'"
> 
>     if ($Ensure -eq "Present" -and $PSBoundParameters.ContainsKey('IconFile') -eq $false)
> ```

Shouldn't we also throw a similar error in the Get if the icon file is not found instead of returning $nullReturn? 
___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1, line 361 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7xRtm2KkDO01sox6N:-MS7xRtm2KkDO01sox6O:bjkrfb2) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1#L361)):*
> ```PowerShell
>     foreach ($mapping in $xmlDoc.DocIcons.ByExtension.Mapping)
>     {
>         if ($mapping.Key -notin $defaultIcons)
> ```

Is there a possibility that someone would have changed the icon associated with a default file type? If so, this would not grab this change. Shouldn't we capture everything here even if it is the default setting? It would help for the monitoring as well. If we capture the default settings, we can use this to detect change drifts made to these defaults.
___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.schema.mof, line 5 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7y3mk4Cc40SFWZ-kZ:-MS7y3ml6nNmt1xWofeB:b-o60urv) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.schema.mof#L5)):*
> ```
> {
>     [Key, Description("Specifies the file type to configure the docicon for")] String FileType;
>     [Write, Description("Specifies the image file for the file type")] String IconFile;
> ```

I recommend we say "Specifies the full path to the image file for the file type"?

**Review by ykuijs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282)* status: all files reviewed, 4 unresolved discussions (waiting on @NikCharlebois)

___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1, line 38 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7qv0T5HIKsqbJkevK:-MS81xBg5XvREzvAXZP3:b-7g0z8y) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1#L38)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Should the file type be passed with the '.' in front. I think not, but some users will pass it. Should we handle this scenario or print an error if they include the '.'?
</blockquote></details>

Great suggestion, I will add a ValidateScript option to the parameter declaration.
___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1, line 128 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7wuqkDPzGm6YV7ZHI:-MS822pU0mkSDLp1OGwa:bf056y2) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1#L128)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Shouldn't we also throw a similar error in the Get if the icon file is not found instead of returning $nullReturn? 
</blockquote></details>

In the past we only threw exceptions when terminating errors occurred in the Get method. This to prevent issues with ReverseDsc. That is why I didn't do this here. This way, the Test method results in False and kick of the Set method.....then there the exception is thrown.
___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1, line 361 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7xRtm2KkDO01sox6N:-MS82dORAl1y19FwNpQ8:b-5f88zi) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1#L361)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Is there a possibility that someone would have changed the icon associated with a default file type? If so, this would not grab this change. Shouldn't we capture everything here even if it is the default setting? It would help for the monitoring as well. If we capture the default settings, we can use this to detect change drifts made to these defaults.
</blockquote></details>

Was in doubt here. Initially wanted to prevent creating a huge number of resources that were default anyways. But I agree that this was not a good idea. Will update this.
___
*[SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.schema.mof, line 5 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-MS7y3mk4Cc40SFWZ-kZ:-MS82vaHBtnVfofyQ2j-:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/ef813b570723d7a0a7ba492a6f6670a9ff7b7cb6/SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.schema.mof#L5)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

I recommend we say "Specifies the full path to the image file for the file type"?
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282#-:-MS8MC9w7Xe4EZmtyAv9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
