### PR TITLE
SPTrustedRootAuthority: Enable specifying both path and thumbprint

### PR DESCRIPTION
**Pull request by jensotto**
#### Pull Request (PR) description

Added possibility to specify path and thumbprint for the certificate so that it is impossible to inadvertently change the certificate on disk either by accident or maliciously. The certificate will be verified to match the specified thumbprint when importing using bot parameters.

#### This Pull Request (PR) fixes the following issues

N/A

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1188)

### CODE REVIEW

**Comment by ykuijs** [comment]
@jensotto Great addition, but you do need to update the unit tests as well. They are now failing and preventing the merge.

**Comment by ykuijs** [comment]
@jensotto Would it be possible to fix the tests on a short notice. Would like to release v4.0 and include your two PR's in the release?

**Comment by jensotto** [comment]
How short? I don't have time to do this earlier than Friday, and it might be late on Friday?

Mvh
Jens Otto
________________________________
Fra: Yorick Kuijs <notifications@github.com>
Sendt: Wednesday, April 22, 2020 1:37:45 PM
Til: dsccommunity/SharePointDsc <SharePointDsc@noreply.github.com>
Kopi: Jens Otto Hatlevold <jensotto@outlook.com>; Mention <mention@noreply.github.com>
Emne: Re: [dsccommunity/SharePointDsc] SPTrustedRootAuthority: Enable specifying both path and thumbprint (#1188)


@jensotto<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjensotto&data=02%7C01%7C%7C6a786bf7c2cd4b18605408d7e6b19441%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637231522671223435&sdata=eUIQT8y5ouYQpUo4qSjKAFJjEy5hX8OlWDYD%2FoTg5hc%3D&reserved=0> Would it be possible to fix the tests on a short notice. Would like to release v4.0 and include your two PR's in the release?

**Comment by ykuijs** [comment]
Friday is no problem!

**Comment by jensotto** [comment]
@ykuijs I get an error when executing '.\build.ps1 -Tasks Build':
ERROR: Cannot find path 'C:\Users\jenso\Source\Repos\SharePointDsc\output\SharePointDsc' because it does not exist.
Do you know what is wrong?

**Comment by ykuijs** [comment]
Please temporarily change line 16 in RequiredModules.psd1 to this:
    Sampler                     = '0.104.0'

This is a known issue in v0.105 which is going to be fixed in the next version.

**Pull request merged**
