### PR TITLE
Support for SQL Authentication

### LINKED ISSUE #1121: Add support for SQL Authentication (e.g. for Azure SQL Managed Instance as a back-end)
Currently SharePointDSC only supports Windows Integrated authentication (which has worked fine in the overwhelming majority of cases). However, some customers have expressed an interest in leveraging Azure SQL Managed Instance as a back-end database for SharePoint in Azure IaaS. While SQL Managed Instances are supported by the product, they don't currently support Windows Integrated auth as they aren't domain-joined. Therefore, we would need to make some fairly significant updates to SharePointDSC to work with Managed Instances (which use SQL authentication - as well as AAD but AFAIK SharePoint can't use that).

I'll be submitting a PR shortly that seeks to address this shortcoming.

### PR DESCRIPTION
**Pull request by brianlala**
#### Pull Request (PR) description

Support to create / connect to Farm and service applications using SQL authentication instead of Windows credentials.

New parameters: UseSQLAuthentication and DatabaseCredentials.

#### This Pull Request (PR) fixes the following issues

    - Fixes #1121

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/sharepointdsc/1126)

### CODE REVIEW

**Comment by ykuijs** [comment]
AppVeyor tTests for 'SPSecureStoreServiceApp' are failing. Do you want me to review now or wait until you fixed the AppVeyor tests?

**Comment by brianlala** [comment]
Thanks for all the comments Yoris! I will review and get back to you shortly :) Agree with most if not all of them. In some cases at least, the descriptions were pre-existing so I didn't modify them but agree it makes sense to review/update.

**Comment by brianlala** [comment]
Also re: AppVeyor tests, I'm totally unfamiliar with it unfortunately so any guidance you have here would be appreciated.

**Comment by ykuijs** [comment]
When you click the "Details" link behind the AppVeyor line, you are redirected to the AppVeyor run/log. 

Above the blue box, you can click "Download the complete log" to download and view the log. When you search for "[-]" you will hit all failed tests.

However since this is all on the SPSecureStoreServiceApp, you can also run the SPSecureStoreServiceApp.Tests.ps1 file (Tests\Unit\SharePointDsc\SharePointDsc.SPSecureStoreServiceApp.Tests.ps1) to run just the single Pester test locally. That will give you all the test results.

**Comment by ykuijs** [comment]
@brianlala Were you able to fix the Pester tests?

**Comment by brianlala** [comment]
Sorry, not yet. Hoping to work on it this week!

**Comment by ykuijs** [comment]
The tests are still failing on the SPSecureStoreServiceApp resource:
image

Like I mentioned in my previous post, you can run these tests locally by browsing to the Unit tests folder (Tests\Unit\SharePointDsc) and running the SharePointDsc.SPSecureStoreServiceApp.Tests.ps1 file.

**Comment by ykuijs** [comment]
Hi @brianlala Merging/rebasing the v4.0-development branch with master was a hell. I finally ended up creating a new branch (v4.0-dev) based of Master and re-implement all changes into that branch.

Can you please target this PR to the new v4.0-dev branch and do a pull making sure your branch is up-to-date as well?

**Comment by brianlala** [comment]
Moved PR to v4.0-dev

**Pull request closed without merging**
