### PR TITLE
Bugfix PR

### LINKED ISSUE #1031: MSFT_SPSearchTopology: Cannot bind argument to parameter 'SearchServiceInstance' because it is null. (FQDN Server Name)
#### Details of the scenario you tried and the problem that is occurring
I'm trying to set the search topology with FQDN Servernames, so i can use my AllNode Data to configure the topology without having a different Configuration for Stage and Produktion.
While troubleshooting I decleared the servernames directly in the configuration.
As a sanity check i ran with hostnames and the ressource creates a Topology as expected.
Every test started with a new SearchService Application without an topology.

#### Verbose logs showing the problem
VERBOSE: [ServerHostName]: LCM:  [ End    Set      ]  [[SPSearchTopology]SP-SearchTopology]  in 0.3930 seconds.
PowerShell DSC resource MSFT_SPSearchTopology  failed to execute Set-TargetResource functionality with error message: Cannot bind argument to parameter 'SearchServiceInstance' because it is null. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : ServerHostName.Domain.tld

#### Suggested solution to the issue
I did some digging into the ressource code. The handling of FQDN Servername works. The `$AllSearchServiceInstances` Variable gets filled properly, but i suspect the issue happens on Line 363 inside the MSFT_SPSearchTopology.psm1. In the previous code the FQDN gets converted to a hostname, but not in this part. Unfortunatly my PowerShell is not good enougth for the `Build up the topology changes for each object type` part and there is a high chance I'm wrong with that. 

```powershell
 # Build up the topology changes for each object type
        @("Admin",
          "Crawler",
          "ContentProcessing",
          "AnalyticsProcessing",
          "QueryProcessing",
"IndexPartition") | ForEach-Object -Process {
....
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SPSearchTopology SP-SearchTopology
            {
                DependsOn = '[SPSearchServiceApp]SP-SearchService'
                PsDscRunAsCredential    = $DSCAccount
                ServiceAppName          = "SearchService_Default"
                Admin                   = @('FQDN#1','FQDN#2')
                Crawler                 = @('FQDN#1','FQDN#2')
                ContentProcessing       = @('FQDN#1','FQDN#2')
                AnalyticsProcessing     = @('FQDN#1','FQDN#2')
                QueryProcessing         = @('FQDN#1','FQDN#2')
                FirstPartitionDirectory = ($ConfigurationData.NonNodeData.SPSearchTopologyIndexPath + '\SearchService_Default\Partition0')
                IndexPartition          = @('FQDN#1','FQDN#2')
```

#### The operating system the target node is running
```PowerShell
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2724.amd64fre.rs1_release.181231-1751
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of SharePoint that is used (e.g. SharePoint 2016)
SharePoint 2016
#### Version and build of PowerShell the target node is running
PSVersion 5.1.14393.2636 
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14393.2636
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.1.0.0

### LINKED ISSUE #1317: SPContentDatabase: trailing / in Webappurl is not removed
#### Details of the scenario you tried and the problem that is occurring
Testing for an exsiting SPContentDatabase fails when 
- it contains a trailing /
- it contains upper case characters

#### Verbose logs showing the problem
    <ConfigurationDrift Source="MSFT_SPContentDatabase">
        <ParametersNotInDesiredState>
            <Param Name="WebAppUrl"><CurrentValue>https://test.domain.com</CurrentValue><DesiredValue>https://test.domain.com/</DesiredValue></Param>
        </ParametersNotInDesiredState>
    </ConfigurationDrift>

AND

    <ConfigurationDrift Source="MSFT_SPContentDatabase">
        <ParametersNotInDesiredState>
            <Param Name="WebAppUrl"><CurrentValue>https://test.domain.com</CurrentValue><DesiredValue>https://TEST.domain.com</DesiredValue></Param>
        </ParametersNotInDesiredState>
    </ConfigurationDrift>

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        $Prefix = "TEST"
        SPContentDatabase CDB_Projects_0001
        {
            DatabaseServer       = $ConfigurationData.NonNodeData.DatabaseServer;
            Enabled              = $True;
            Ensure               = "Present";
            WarningSiteCount     = 280;
            MaximumSiteCount     = 300;
            Name                 = $Prefix + "_CDB_Projects_0001";
            PsDscRunAsCredential = $SPSetupAccount
            WebAppUrl            = "https://" + $Prefix +".domain.com/"
        }```

#### The operating system the target node is running

#### Version and build of PowerShell the target node is running

#### Version of the DSC module that was used
4.5.1

### LINKED ISSUE #1322: MSFT_SPSearchTopology - Fails if not executed on server with index role
#### Details of the scenario you tried and the problem that is occurring
Creating a search topology fails when trying to create an index partition on a server which does not have the index role.

#### Verbose logs showing the problem
DSC resource MSFT_SPSearchTopology failed to execute Set-TargetResource functionality with error message:
Cannot bind parametet 'RootDirectory' to the target. Exception setting "RootDirectory". Could not find part of the path "G:\SEARCHINDEX\0".

#### Suggested solution to the issue
Create the root directory using DSC File resource, create file share and use share path for the property 'RootDirectory' just before crreating the search topology.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Search = @{
    Provision                    = $true
       Publish                    = $true
    Name                         = "Search Service Application"
       ApplicationPoolName = "SharePoint Search Applications"
    DatabaseName           = "SEARCH_DB_001"
       DatabaseServer          = "SEARCH_DB_SERVER"
       CloudSSA                   = $false
    SearchCenterUrl       = https://sharepoint.contoso.com/search
    SearchTopology        = @{
        Admin                           = @("Server1","Server2")
        Crawler                  = @("Server1","Server2")
        ContentProcessing = @("Server2","Server2")
        AnalyticsProcessing = @("Server2","Server2")
        QueryProcessing   = @("Server1","Server2")
    }
    SearchIndexes = @(
        @{
            Servers              = @("Server3","Server4")
            Index                = 0
            RootDirectory = "G:\SEARCHINDEX\0"
        }
} 
```

#### The operating system the target node is running
OS: Windows Server 2019 EN-US
#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used
4.2.0

### LINKED ISSUE #1326: [SPManagedMetaDataServiceApp] When a ProxyName is not specified and the proxy is not created, the resource does not detect it correctly
#### Details of the scenario you tried and the problem that is occurring
If the proxy hasn't been created (for whatever reason), the Get method returns ProxyName = "". 
https://github.com/dsccommunity/SharePointDsc/blob/852a3779db1166cb5412451a3463992b4efa59f1/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L108-L115

The Set method checks if the ProxyName returned from the Get method is not $null and if so, use the returned name.
https://github.com/dsccommunity/SharePointDsc/blob/852a3779db1166cb5412451a3463992b4efa59f1/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L350-L354

In that case the to be created proxy name is "". Later in the Set method, it checks if the new name (which is empty) is equal to the returned name (which is also empty):
https://github.com/dsccommunity/SharePointDsc/blob/852a3779db1166cb5412451a3463992b4efa59f1/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L425

This is causing the proxy not to be created.

#### Suggested solution to the issue
Check using [String]::IsNullOrEmpty()

#### Version of the DSC module that was used
Dev

### PR DESCRIPTION
**Pull request by ykuijs**
#### Pull Request (PR) description

This PR fixes several bug in SharePointDsc

#### This Pull Request (PR) fixes the following issues

- Fixes #1031 
- Fixes #1317 
- Fixes #1322 
- Fixes #1326 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330)

### CODE REVIEW

**Comment by ykuijs** [comment]
@NikCharlebois Up for review?

**Review by NikCharlebois — COMMENTED** [review]
Typo + Logic error

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-:-Me4sbLw1loMdj8bjS-T:b-s6ipja)* status: all files reviewed, 2 unresolved discussions (waiting on @ykuijs)

___
*[CHANGELOG.md, line 20 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-Me4rYsQEFRx8To9Cfjv:-Me4rYsQEFRx8To9Cfjw:bkjjqqj) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/7936d42cc86e69ae8d72a00dcd7c2ea63bcb1e2d/CHANGELOG.md#L20)):*
> ```Markdown
> 
> - SPContentDatabase
>   - Fixed issue where WebAppUrl in the Desired State would could the test to fail, always resulting
> ```

Should be 'would cause'
___
*[SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 351 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-Me4rnsw0jqp3W1an1wk:-Me4rnsw0jqp3W1an1wl:b-ywkff4) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/7936d42cc86e69ae8d72a00dcd7c2ea63bcb1e2d/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L351)):*
> ```PowerShell
> 
>     $pName = "$Name Proxy"
>     if ([String]::IsNullOrEmpty($result.ProxyName))
> ```

The original check was to ensure the value was not null. This one is to ensure it is (the opposite). I think it should be

if (-not [String]::IsNullOrEmpty($result.ProxyName)) 

Instead

**Review by ykuijs — COMMENTED** [review]
Great spot for the Null check!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-:-Me4ySga9dgZvKluydGJ:bohec9y)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @NikCharlebois)

___
*[CHANGELOG.md, line 20 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-Me4rYsQEFRx8To9Cfjv:-Me4yQDp3YIXmJchU8HL:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/7936d42cc86e69ae8d72a00dcd7c2ea63bcb1e2d/CHANGELOG.md#L20)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Should be 'would cause'
</blockquote></details>

Done.
___
*[SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1, line 351 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-Me4rnsw0jqp3W1an1wk:-Me4yRkH82LOHYhlE868:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/7936d42cc86e69ae8d72a00dcd7c2ea63bcb1e2d/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1#L351)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

The original check was to ensure the value was not null. This one is to ensure it is (the opposite). I think it should be

if (-not [String]::IsNullOrEmpty($result.ProxyName)) 

Instead
</blockquote></details>

Done.

**Review by NikCharlebois — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1330#-:-Me4zhgK698Oxx9BqYdP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ykuijs)

**Pull request merged**
