### PR TITLE
[SPFarm] Ensure that flights are registered in SharePoint Subscription

### PR DESCRIPTION
**Pull request by Yvand**
#### Pull Request (PR) description

SharePoint Subscription introduced flighting. When creating a farm using PowerShell, one new step is to run cmdlet [Update-SPFlightsConfigFile](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/update-spflightsconfigfile?view=sharepoint-server-ps) to ensure that all flights in current build are registered in the configuration database.

#### This Pull Request (PR) fixes the following issues

In SharePoint Subscription, ensure that all flights available in current build are registered in the configuration database

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1428)

### CODE REVIEW

**Comment by ykuijs** [comment]
The SPSE unit test failed. I think because the Get-SPDscRegistryKey function isn't mocked and therefore doesn't return any value. This is causing the Join-Path to fail. Please create proper mocks for Get-SPDscRegistryKey, Test-Path and Update-SPFlightsConfigFile.

**Comment by ykuijs** [comment]
This last change broke the unit tests for the other versions as well 😉 Looks like something is not going well here. You can run the tests locally, by just running the tests ps1 file.

I see that you have implemented an if statement in the code. It is also possible to create multiple mock using [ParameterFilters](https://pester.dev/docs/commands/Mock#-parameterfilter). That way you can mock the same function multiple times, once for each scenario.

**Comment by Yvand** [comment]
Indeed, it is because I should Mock [`Update-SPFlightsConfigFile`](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/update-spflightsconfigfile?view=sharepoint-server-ps) only if current environment is SharePoint SE.

I already thought about it but I didn't know how to do it, but I also didn't know about `ParameterFilters`, hopefully it will allow me to fix that, I'll take a look asap

**Comment by ykuijs** [comment]
You can check the used version number like we do here:
https://github.com/dsccommunity/SharePointDsc/blob/fdb9a4a15b8ca78f291a612efcd8774dfd8816aa/tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheService.Tests.ps1#L427-L428

**Review by ykuijs — APPROVED** [review]
LGTM

**Pull request merged**
