### PR TITLE
Add parameter SkipRegisterAsDistributedCacheHost to SPFarm

### PR DESCRIPTION
**Pull request by Yvand**
#### Pull Request (PR) description

Add parameter SkipRegisterAsDistributedCacheHost to SPFarm to allow to explicitely set it

#### This Pull Request (PR) fixes the following issues

- Related to https://github.com/dsccommunity/SharePointDsc/issues/1321

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325)

### CODE REVIEW

**Review by ykuijs — CHANGES_REQUESTED** [review]
Thanks for submitting this PR. One small comment to make sure the parameter is applied correctly.

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325#-:-McPA9Z3612kC-sqgK1_:bhr3nmt)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Yvand)

___
*[SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 477 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325#-McP9dWs1Up40nuJM7Nh:-McP9dWs1Up40nuJM7Ni:b8ie8ed) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/9f8a91562fc3814c927dad4e697a6c0da5ab3626/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L477)):*
> ```PowerShell
>         throw $message
>     }
> ```

Default values are not included in the $PSBoundParameters variable. Please add the following line here:
```PowerShell
$PSBoundParameters.SkipRegisterAsDistributedCacheHost = $SkipRegisterAsDistributedCacheHost
```

That way, the parameter is added to the variable, also when it is not specified and has the default value of $false

**Review by ykuijs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Yvand)

___
*[SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 95 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325#-McPAwIS09D2IJqE0OwP:-McPAwIS09D2IJqE0OwQ:b-r7ruq3) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/9f8a91562fc3814c927dad4e697a6c0da5ab3626/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L95)):*
> ```PowerShell
>         [Parameter()]
>         [System.Boolean]
>         $SkipRegisterAsDistributedCacheHost = $false,
> ```

Please set the default value to $true, so the way the resource functions currently is not changed (so this isn't a breaking change ;-))

**Comment by Yvand** [comment]
___
*[SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 477 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325#-McP9dWs1Up40nuJM7Nh:-McPKZ6XATr1eqmbU1Ge:bhmhk5s) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/9f8a91562fc3814c927dad4e697a6c0da5ab3626/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L477)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Default values are not included in the $PSBoundParameters variable. Please add the following line here:
```PowerShell
$PSBoundParameters.SkipRegisterAsDistributedCacheHost = $SkipRegisterAsDistributedCacheHost
```

That way, the parameter is added to the variable, also when it is not specified and has the default value of $false
</blockquote></details>

Nice catch! Done.

**Review by Yvand — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ykuijs)

___
*[SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1, line 95 at r1](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325#-McPAwIS09D2IJqE0OwP:-McPKfmE7TYAFWSrkE8O:b-896fix) ([raw file](https://github.com/dsccommunity/sharepointdsc/blob/9f8a91562fc3814c927dad4e697a6c0da5ab3626/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1#L95)):*
<details><summary><i>Previously, ykuijs (Yorick Kuijs) wrote…</i></summary><blockquote>

Please set the default value to $true, so the way the resource functions currently is not changed (so this isn't a breaking change ;-))
</blockquote></details>

Done.

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325#-:-McPLwmu4CX6pGkYKVgI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yvand)

**Review by ykuijs — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yvand)

**Pull request merged**
